// This file was modified by Oracle on June 1, 2021.
// An entry was created for a new error reported by the MySQL server due to
// client inactivity.
// Modifications copyright (c) 2021, Oracle and/or its affiliates.

export const EE_CANTCREATEFILE = 1;
export const EE_READ = 2;
export const EE_WRITE = 3;
export const EE_BADCLOSE = 4;
export const EE_OUTOFMEMORY = 5;
export const EE_DELETE = 6;
export const EE_LINK = 7;
export const EE_EOFERR = 9;
export const EE_CANTLOCK = 10;
export const EE_CANTUNLOCK = 11;
export const EE_DIR = 12;
export const EE_STAT = 13;
export const EE_CANT_CHSIZE = 14;
export const EE_CANT_OPEN_STREAM = 15;
export const EE_GETWD = 16;
export const EE_SETWD = 17;
export const EE_LINK_WARNING = 18;
export const EE_OPEN_WARNING = 19;
export const EE_DISK_FULL = 20;
export const EE_CANT_MKDIR = 21;
export const EE_UNKNOWN_CHARSET = 22;
export const EE_OUT_OF_FILERESOURCES = 23;
export const EE_CANT_READLINK = 24;
export const EE_CANT_SYMLINK = 25;
export const EE_REALPATH = 26;
export const EE_SYNC = 27;
export const EE_UNKNOWN_COLLATION = 28;
export const EE_FILENOTFOUND = 29;
export const EE_FILE_NOT_CLOSED = 30;
export const EE_CHANGE_OWNERSHIP = 31;
export const EE_CHANGE_PERMISSIONS = 32;
export const EE_CANT_SEEK = 33;
export const HA_ERR_KEY_NOT_FOUND = 120;
export const HA_ERR_FOUND_DUPP_KEY = 121;
export const HA_ERR_INTERNAL_ERROR = 122;
export const HA_ERR_RECORD_CHANGED = 123;
export const HA_ERR_WRONG_INDEX = 124;
export const HA_ERR_CRASHED = 126;
export const HA_ERR_WRONG_IN_RECORD = 127;
export const HA_ERR_OUT_OF_MEM = 128;
export const HA_ERR_NOT_A_TABLE = 130;
export const HA_ERR_WRONG_COMMAND = 131;
export const HA_ERR_OLD_FILE = 132;
export const HA_ERR_NO_ACTIVE_RECORD = 133;
export const HA_ERR_RECORD_DELETED = 134;
export const HA_ERR_RECORD_FILE_FULL = 135;
export const HA_ERR_INDEX_FILE_FULL = 136;
export const HA_ERR_END_OF_FILE = 137;
export const HA_ERR_UNSUPPORTED = 138;
export const HA_ERR_TO_BIG_ROW = 139;
export const HA_WRONG_CREATE_OPTION = 140;
export const HA_ERR_FOUND_DUPP_UNIQUE = 141;
export const HA_ERR_UNKNOWN_CHARSET = 142;
export const HA_ERR_WRONG_MRG_TABLE_DEF = 143;
export const HA_ERR_CRASHED_ON_REPAIR = 144;
export const HA_ERR_CRASHED_ON_USAGE = 145;
export const HA_ERR_LOCK_WAIT_TIMEOUT = 146;
export const HA_ERR_LOCK_TABLE_FULL = 147;
export const HA_ERR_READ_ONLY_TRANSACTION = 148;
export const HA_ERR_LOCK_DEADLOCK = 149;
export const HA_ERR_CANNOT_ADD_FOREIGN = 150;
export const HA_ERR_NO_REFERENCED_ROW = 151;
export const HA_ERR_ROW_IS_REFERENCED = 152;
export const HA_ERR_NO_SAVEPOINT = 153;
export const HA_ERR_NON_UNIQUE_BLOCK_SIZE = 154;
export const HA_ERR_NO_SUCH_TABLE = 155;
export const HA_ERR_TABLE_EXIST = 156;
export const HA_ERR_NO_CONNECTION = 157;
export const HA_ERR_NULL_IN_SPATIAL = 158;
export const HA_ERR_TABLE_DEF_CHANGED = 159;
export const HA_ERR_NO_PARTITION_FOUND = 160;
export const HA_ERR_RBR_LOGGING_FAILED = 161;
export const HA_ERR_DROP_INDEX_FK = 162;
export const HA_ERR_FOREIGN_DUPLICATE_KEY = 163;
export const HA_ERR_TABLE_NEEDS_UPGRADE = 164;
export const HA_ERR_TABLE_READONLY = 165;
export const HA_ERR_AUTOINC_READ_FAILED = 166;
export const HA_ERR_AUTOINC_ERANGE = 167;
export const HA_ERR_GENERIC = 168;
export const HA_ERR_RECORD_IS_THE_SAME = 169;
export const HA_ERR_LOGGING_IMPOSSIBLE = 170;
export const HA_ERR_CORRUPT_EVENT = 171;
export const HA_ERR_NEW_FILE = 172;
export const HA_ERR_ROWS_EVENT_APPLY = 173;
export const HA_ERR_INITIALIZATION = 174;
export const HA_ERR_FILE_TOO_SHORT = 175;
export const HA_ERR_WRONG_CRC = 176;
export const HA_ERR_TOO_MANY_CONCURRENT_TRXS = 177;
export const HA_ERR_NOT_IN_LOCK_PARTITIONS = 178;
export const HA_ERR_INDEX_COL_TOO_LONG = 179;
export const HA_ERR_INDEX_CORRUPT = 180;
export const HA_ERR_UNDO_REC_TOO_BIG = 181;
export const HA_FTS_INVALID_DOCID = 182;
export const HA_ERR_TABLE_IN_FK_CHECK = 183;
export const HA_ERR_TABLESPACE_EXISTS = 184;
export const HA_ERR_TOO_MANY_FIELDS = 185;
export const HA_ERR_ROW_IN_WRONG_PARTITION = 186;
export const HA_ERR_INNODB_READ_ONLY = 187;
export const HA_ERR_FTS_EXCEED_RESULT_CACHE_LIMIT = 188;
export const HA_ERR_TEMP_FILE_WRITE_FAILURE = 189;
export const HA_ERR_INNODB_FORCED_RECOVERY = 190;
export const HA_ERR_FTS_TOO_MANY_WORDS_IN_PHRASE = 191;
export const ER_HASHCHK = 1000;
export const ER_NISAMCHK = 1001;
export const ER_NO = 1002;
export const ER_YES = 1003;
export const ER_CANT_CREATE_FILE = 1004;
export const ER_CANT_CREATE_TABLE = 1005;
export const ER_CANT_CREATE_DB = 1006;
export const ER_DB_CREATE_EXISTS = 1007;
export const ER_DB_DROP_EXISTS = 1008;
export const ER_DB_DROP_DELETE = 1009;
export const ER_DB_DROP_RMDIR = 1010;
export const ER_CANT_DELETE_FILE = 1011;
export const ER_CANT_FIND_SYSTEM_REC = 1012;
export const ER_CANT_GET_STAT = 1013;
export const ER_CANT_GET_WD = 1014;
export const ER_CANT_LOCK = 1015;
export const ER_CANT_OPEN_FILE = 1016;
export const ER_FILE_NOT_FOUND = 1017;
export const ER_CANT_READ_DIR = 1018;
export const ER_CANT_SET_WD = 1019;
export const ER_CHECKREAD = 1020;
export const ER_DISK_FULL = 1021;
export const ER_DUP_KEY = 1022;
export const ER_ERROR_ON_CLOSE = 1023;
export const ER_ERROR_ON_READ = 1024;
export const ER_ERROR_ON_RENAME = 1025;
export const ER_ERROR_ON_WRITE = 1026;
export const ER_FILE_USED = 1027;
export const ER_FILSORT_ABORT = 1028;
export const ER_FORM_NOT_FOUND = 1029;
export const ER_GET_ERRNO = 1030;
export const ER_ILLEGAL_HA = 1031;
export const ER_KEY_NOT_FOUND = 1032;
export const ER_NOT_FORM_FILE = 1033;
export const ER_NOT_KEYFILE = 1034;
export const ER_OLD_KEYFILE = 1035;
export const ER_OPEN_AS_READONLY = 1036;
export const ER_OUTOFMEMORY = 1037;
export const ER_OUT_OF_SORTMEMORY = 1038;
export const ER_UNEXPECTED_EOF = 1039;
export const ER_CON_COUNT_ERROR = 1040;
export const ER_OUT_OF_RESOURCES = 1041;
export const ER_BAD_HOST_ERROR = 1042;
export const ER_HANDSHAKE_ERROR = 1043;
export const ER_DBACCESS_DENIED_ERROR = 1044;
export const ER_ACCESS_DENIED_ERROR = 1045;
export const ER_NO_DB_ERROR = 1046;
export const ER_UNKNOWN_COM_ERROR = 1047;
export const ER_BAD_NULL_ERROR = 1048;
export const ER_BAD_DB_ERROR = 1049;
export const ER_TABLE_EXISTS_ERROR = 1050;
export const ER_BAD_TABLE_ERROR = 1051;
export const ER_NON_UNIQ_ERROR = 1052;
export const ER_SERVER_SHUTDOWN = 1053;
export const ER_BAD_FIELD_ERROR = 1054;
export const ER_WRONG_FIELD_WITH_GROUP = 1055;
export const ER_WRONG_GROUP_FIELD = 1056;
export const ER_WRONG_SUM_SELECT = 1057;
export const ER_WRONG_VALUE_COUNT = 1058;
export const ER_TOO_LONG_IDENT = 1059;
export const ER_DUP_FIELDNAME = 1060;
export const ER_DUP_KEYNAME = 1061;
export const ER_DUP_ENTRY = 1062;
export const ER_WRONG_FIELD_SPEC = 1063;
export const ER_PARSE_ERROR = 1064;
export const ER_EMPTY_QUERY = 1065;
export const ER_NONUNIQ_TABLE = 1066;
export const ER_INVALID_DEFAULT = 1067;
export const ER_MULTIPLE_PRI_KEY = 1068;
export const ER_TOO_MANY_KEYS = 1069;
export const ER_TOO_MANY_KEY_PARTS = 1070;
export const ER_TOO_LONG_KEY = 1071;
export const ER_KEY_COLUMN_DOES_NOT_EXITS = 1072;
export const ER_BLOB_USED_AS_KEY = 1073;
export const ER_TOO_BIG_FIELDLENGTH = 1074;
export const ER_WRONG_AUTO_KEY = 1075;
export const ER_READY = 1076;
export const ER_NORMAL_SHUTDOWN = 1077;
export const ER_GOT_SIGNAL = 1078;
export const ER_SHUTDOWN_COMPLETE = 1079;
export const ER_FORCING_CLOSE = 1080;
export const ER_IPSOCK_ERROR = 1081;
export const ER_NO_SUCH_INDEX = 1082;
export const ER_WRONG_FIELD_TERMINATORS = 1083;
export const ER_BLOBS_AND_NO_TERMINATED = 1084;
export const ER_TEXTFILE_NOT_READABLE = 1085;
export const ER_FILE_EXISTS_ERROR = 1086;
export const ER_LOAD_INFO = 1087;
export const ER_ALTER_INFO = 1088;
export const ER_WRONG_SUB_KEY = 1089;
export const ER_CANT_REMOVE_ALL_FIELDS = 1090;
export const ER_CANT_DROP_FIELD_OR_KEY = 1091;
export const ER_INSERT_INFO = 1092;
export const ER_UPDATE_TABLE_USED = 1093;
export const ER_NO_SUCH_THREAD = 1094;
export const ER_KILL_DENIED_ERROR = 1095;
export const ER_NO_TABLES_USED = 1096;
export const ER_TOO_BIG_SET = 1097;
export const ER_NO_UNIQUE_LOGFILE = 1098;
export const ER_TABLE_NOT_LOCKED_FOR_WRITE = 1099;
export const ER_TABLE_NOT_LOCKED = 1100;
export const ER_BLOB_CANT_HAVE_DEFAULT = 1101;
export const ER_WRONG_DB_NAME = 1102;
export const ER_WRONG_TABLE_NAME = 1103;
export const ER_TOO_BIG_SELECT = 1104;
export const ER_UNKNOWN_ERROR = 1105;
export const ER_UNKNOWN_PROCEDURE = 1106;
export const ER_WRONG_PARAMCOUNT_TO_PROCEDURE = 1107;
export const ER_WRONG_PARAMETERS_TO_PROCEDURE = 1108;
export const ER_UNKNOWN_TABLE = 1109;
export const ER_FIELD_SPECIFIED_TWICE = 1110;
export const ER_INVALID_GROUP_FUNC_USE = 1111;
export const ER_UNSUPPORTED_EXTENSION = 1112;
export const ER_TABLE_MUST_HAVE_COLUMNS = 1113;
export const ER_RECORD_FILE_FULL = 1114;
export const ER_UNKNOWN_CHARACTER_SET = 1115;
export const ER_TOO_MANY_TABLES = 1116;
export const ER_TOO_MANY_FIELDS = 1117;
export const ER_TOO_BIG_ROWSIZE = 1118;
export const ER_STACK_OVERRUN = 1119;
export const ER_WRONG_OUTER_JOIN = 1120;
export const ER_NULL_COLUMN_IN_INDEX = 1121;
export const ER_CANT_FIND_UDF = 1122;
export const ER_CANT_INITIALIZE_UDF = 1123;
export const ER_UDF_NO_PATHS = 1124;
export const ER_UDF_EXISTS = 1125;
export const ER_CANT_OPEN_LIBRARY = 1126;
export const ER_CANT_FIND_DL_ENTRY = 1127;
export const ER_FUNCTION_NOT_DEFINED = 1128;
export const ER_HOST_IS_BLOCKED = 1129;
export const ER_HOST_NOT_PRIVILEGED = 1130;
export const ER_PASSWORD_ANONYMOUS_USER = 1131;
export const ER_PASSWORD_NOT_ALLOWED = 1132;
export const ER_PASSWORD_NO_MATCH = 1133;
export const ER_UPDATE_INFO = 1134;
export const ER_CANT_CREATE_THREAD = 1135;
export const ER_WRONG_VALUE_COUNT_ON_ROW = 1136;
export const ER_CANT_REOPEN_TABLE = 1137;
export const ER_INVALID_USE_OF_NULL = 1138;
export const ER_REGEXP_ERROR = 1139;
export const ER_MIX_OF_GROUP_FUNC_AND_FIELDS = 1140;
export const ER_NONEXISTING_GRANT = 1141;
export const ER_TABLEACCESS_DENIED_ERROR = 1142;
export const ER_COLUMNACCESS_DENIED_ERROR = 1143;
export const ER_ILLEGAL_GRANT_FOR_TABLE = 1144;
export const ER_GRANT_WRONG_HOST_OR_USER = 1145;
export const ER_NO_SUCH_TABLE = 1146;
export const ER_NONEXISTING_TABLE_GRANT = 1147;
export const ER_NOT_ALLOWED_COMMAND = 1148;
export const ER_SYNTAX_ERROR = 1149;
export const ER_DELAYED_CANT_CHANGE_LOCK = 1150;
export const ER_TOO_MANY_DELAYED_THREADS = 1151;
export const ER_ABORTING_CONNECTION = 1152;
export const ER_NET_PACKET_TOO_LARGE = 1153;
export const ER_NET_READ_ERROR_FROM_PIPE = 1154;
export const ER_NET_FCNTL_ERROR = 1155;
export const ER_NET_PACKETS_OUT_OF_ORDER = 1156;
export const ER_NET_UNCOMPRESS_ERROR = 1157;
export const ER_NET_READ_ERROR = 1158;
export const ER_NET_READ_INTERRUPTED = 1159;
export const ER_NET_ERROR_ON_WRITE = 1160;
export const ER_NET_WRITE_INTERRUPTED = 1161;
export const ER_TOO_LONG_STRING = 1162;
export const ER_TABLE_CANT_HANDLE_BLOB = 1163;
export const ER_TABLE_CANT_HANDLE_AUTO_INCREMENT = 1164;
export const ER_DELAYED_INSERT_TABLE_LOCKED = 1165;
export const ER_WRONG_COLUMN_NAME = 1166;
export const ER_WRONG_KEY_COLUMN = 1167;
export const ER_WRONG_MRG_TABLE = 1168;
export const ER_DUP_UNIQUE = 1169;
export const ER_BLOB_KEY_WITHOUT_LENGTH = 1170;
export const ER_PRIMARY_CANT_HAVE_NULL = 1171;
export const ER_TOO_MANY_ROWS = 1172;
export const ER_REQUIRES_PRIMARY_KEY = 1173;
export const ER_NO_RAID_COMPILED = 1174;
export const ER_UPDATE_WITHOUT_KEY_IN_SAFE_MODE = 1175;
export const ER_KEY_DOES_NOT_EXITS = 1176;
export const ER_CHECK_NO_SUCH_TABLE = 1177;
export const ER_CHECK_NOT_IMPLEMENTED = 1178;
export const ER_CANT_DO_THIS_DURING_AN_TRANSACTION = 1179;
export const ER_ERROR_DURING_COMMIT = 1180;
export const ER_ERROR_DURING_ROLLBACK = 1181;
export const ER_ERROR_DURING_FLUSH_LOGS = 1182;
export const ER_ERROR_DURING_CHECKPOINT = 1183;
export const ER_NEW_ABORTING_CONNECTION = 1184;
export const ER_DUMP_NOT_IMPLEMENTED = 1185;
export const ER_FLUSH_MASTER_BINLOG_CLOSED = 1186; // deprecated
export const ER_FLUSH_SOURCE_BINLOG_CLOSED = 1186;
export const ER_INDEX_REBUILD = 1187;
export const ER_MASTER = 1188; // deprecated
export const ER_SOURCE = 1188;
export const ER_MASTER_NET_READ = 1189; // deprecated
export const ER_SOURCE_NET_READ = 1189;
export const ER_MASTER_NET_WRITE = 1190; // deprecated
export const ER_SOURCE_NET_WRITE = 1190;
export const ER_FT_MATCHING_KEY_NOT_FOUND = 1191;
export const ER_LOCK_OR_ACTIVE_TRANSACTION = 1192;
export const ER_UNKNOWN_SYSTEM_VARIABLE = 1193;
export const ER_CRASHED_ON_USAGE = 1194;
export const ER_CRASHED_ON_REPAIR = 1195;
export const ER_WARNING_NOT_COMPLETE_ROLLBACK = 1196;
export const ER_TRANS_CACHE_FULL = 1197;
export const ER_SLAVE_MUST_STOP = 1198; // deprecated
export const ER_REPLICA_MUST_STOP = 1198;
export const ER_SLAVE_NOT_RUNNING = 1199; // deprecated
export const ER_REPLICA_NOT_RUNNING = 1199;
export const ER_BAD_SLAVE = 1200; // deprecated
export const ER_BAD_REPLICA = 1200;
export const ER_MASTER_INFO = 1201; // deprecated
export const ER_SOURCE_INFO = 1201;
export const ER_SLAVE_THREAD = 1202; // deprecated
export const ER_REPLICA_THREAD = 1202;
export const ER_TOO_MANY_USER_CONNECTIONS = 1203;
export const ER_SET_CONSTANTS_ONLY = 1204;
export const ER_LOCK_WAIT_TIMEOUT = 1205;
export const ER_LOCK_TABLE_FULL = 1206;
export const ER_READ_ONLY_TRANSACTION = 1207;
export const ER_DROP_DB_WITH_READ_LOCK = 1208;
export const ER_CREATE_DB_WITH_READ_LOCK = 1209;
export const ER_WRONG_ARGUMENTS = 1210;
export const ER_NO_PERMISSION_TO_CREATE_USER = 1211;
export const ER_UNION_TABLES_IN_DIFFERENT_DIR = 1212;
export const ER_LOCK_DEADLOCK = 1213;
export const ER_TABLE_CANT_HANDLE_FT = 1214;
export const ER_CANNOT_ADD_FOREIGN = 1215;
export const ER_NO_REFERENCED_ROW = 1216;
export const ER_ROW_IS_REFERENCED = 1217;
export const ER_CONNECT_TO_MASTER = 1218; // deprecated
export const ER_CONNECT_TO_SOURCE = 1218;
export const ER_QUERY_ON_MASTER = 1219; // deprecated
export const ER_QUERY_ON_SOURCE = 1219;
export const ER_ERROR_WHEN_EXECUTING_COMMAND = 1220;
export const ER_WRONG_USAGE = 1221;
export const ER_WRONG_NUMBER_OF_COLUMNS_IN_SELECT = 1222;
export const ER_CANT_UPDATE_WITH_READLOCK = 1223;
export const ER_MIXING_NOT_ALLOWED = 1224;
export const ER_DUP_ARGUMENT = 1225;
export const ER_USER_LIMIT_REACHED = 1226;
export const ER_SPECIFIC_ACCESS_DENIED_ERROR = 1227;
export const ER_LOCAL_VARIABLE = 1228;
export const ER_GLOBAL_VARIABLE = 1229;
export const ER_NO_DEFAULT = 1230;
export const ER_WRONG_VALUE_FOR_VAR = 1231;
export const ER_WRONG_TYPE_FOR_VAR = 1232;
export const ER_VAR_CANT_BE_READ = 1233;
export const ER_CANT_USE_OPTION_HERE = 1234;
export const ER_NOT_SUPPORTED_YET = 1235;
export const ER_MASTER_FATAL_ERROR_READING_BINLOG = 1236; // deprecated
export const ER_SOURCE_FATAL_ERROR_READING_BINLOG = 1236;
export const ER_SLAVE_IGNORED_TABLE = 1237; // deprecated
export const ER_REPLICA_IGNORED_TABLE = 1237;
export const ER_INCORRECT_GLOBAL_LOCAL_VAR = 1238;
export const ER_WRONG_FK_DEF = 1239;
export const ER_KEY_REF_DO_NOT_MATCH_TABLE_REF = 1240;
export const ER_OPERAND_COLUMNS = 1241;
export const ER_SUBQUERY_NO_1_ROW = 1242;
export const ER_UNKNOWN_STMT_HANDLER = 1243;
export const ER_CORRUPT_HELP_DB = 1244;
export const ER_CYCLIC_REFERENCE = 1245;
export const ER_AUTO_CONVERT = 1246;
export const ER_ILLEGAL_REFERENCE = 1247;
export const ER_DERIVED_MUST_HAVE_ALIAS = 1248;
export const ER_SELECT_REDUCED = 1249;
export const ER_TABLENAME_NOT_ALLOWED_HERE = 1250;
export const ER_NOT_SUPPORTED_AUTH_MODE = 1251;
export const ER_SPATIAL_CANT_HAVE_NULL = 1252;
export const ER_COLLATION_CHARSET_MISMATCH = 1253;
export const ER_SLAVE_WAS_RUNNING = 1254; // deprecated
export const ER_REPLICA_WAS_RUNNING = 1254;
export const ER_SLAVE_WAS_NOT_RUNNING = 1255; // deprecated
export const ER_REPLICA_WAS_NOT_RUNNING = 1255;
export const ER_TOO_BIG_FOR_UNCOMPRESS = 1256;
export const ER_ZLIB_Z_MEM_ERROR = 1257;
export const ER_ZLIB_Z_BUF_ERROR = 1258;
export const ER_ZLIB_Z_DATA_ERROR = 1259;
export const ER_CUT_VALUE_GROUP_CONCAT = 1260;
export const ER_WARN_TOO_FEW_RECORDS = 1261;
export const ER_WARN_TOO_MANY_RECORDS = 1262;
export const ER_WARN_NULL_TO_NOTNULL = 1263;
export const ER_WARN_DATA_OUT_OF_RANGE = 1264;
export const ER_WARN_DATA_TRUNCATED = 1265;
export const ER_WARN_USING_OTHER_HANDLER = 1266;
export const ER_CANT_AGGREGATE_2COLLATIONS = 1267;
export const ER_DROP_USER = 1268;
export const ER_REVOKE_GRANTS = 1269;
export const ER_CANT_AGGREGATE_3COLLATIONS = 1270;
export const ER_CANT_AGGREGATE_NCOLLATIONS = 1271;
export const ER_VARIABLE_IS_NOT_STRUCT = 1272;
export const ER_UNKNOWN_COLLATION = 1273;
export const ER_SLAVE_IGNORED_SSL_PARAMS = 1274; // deprecated
export const ER_REPLICA_IGNORED_SSL_PARAMS = 1274;
export const ER_SERVER_IS_IN_SECURE_AUTH_MODE = 1275;
export const ER_WARN_FIELD_RESOLVED = 1276;
export const ER_BAD_SLAVE_UNTIL_COND = 1277; // deprecated
export const ER_BAD_REPLICA_UNTIL_COND = 1277;
export const ER_MISSING_SKIP_SLAVE = 1278; // deprecated
export const ER_MISSING_SKIP_REPLICA = 1278;
export const ER_UNTIL_COND_IGNORED = 1279;
export const ER_WRONG_NAME_FOR_INDEX = 1280;
export const ER_WRONG_NAME_FOR_CATALOG = 1281;
export const ER_WARN_QC_RESIZE = 1282;
export const ER_BAD_FT_COLUMN = 1283;
export const ER_UNKNOWN_KEY_CACHE = 1284;
export const ER_WARN_HOSTNAME_WONT_WORK = 1285;
export const ER_UNKNOWN_STORAGE_ENGINE = 1286;
export const ER_WARN_DEPRECATED_SYNTAX = 1287;
export const ER_NON_UPDATABLE_TABLE = 1288;
export const ER_FEATURE_DISABLED = 1289;
export const ER_OPTION_PREVENTS_STATEMENT = 1290;
export const ER_DUPLICATED_VALUE_IN_TYPE = 1291;
export const ER_TRUNCATED_WRONG_VALUE = 1292;
export const ER_TOO_MUCH_AUTO_TIMESTAMP_COLS = 1293;
export const ER_INVALID_ON_UPDATE = 1294;
export const ER_UNSUPPORTED_PS = 1295;
export const ER_GET_ERRMSG = 1296;
export const ER_GET_TEMPORARY_ERRMSG = 1297;
export const ER_UNKNOWN_TIME_ZONE = 1298;
export const ER_WARN_INVALID_TIMESTAMP = 1299;
export const ER_INVALID_CHARACTER_STRING = 1300;
export const ER_WARN_ALLOWED_PACKET_OVERFLOWED = 1301;
export const ER_CONFLICTING_DECLARATIONS = 1302;
export const ER_SP_NO_RECURSIVE_CREATE = 1303;
export const ER_SP_ALREADY_EXISTS = 1304;
export const ER_SP_DOES_NOT_EXIST = 1305;
export const ER_SP_DROP_FAILED = 1306;
export const ER_SP_STORE_FAILED = 1307;
export const ER_SP_LILABEL_MISMATCH = 1308;
export const ER_SP_LABEL_REDEFINE = 1309;
export const ER_SP_LABEL_MISMATCH = 1310;
export const ER_SP_UNINIT_VAR = 1311;
export const ER_SP_BADSELECT = 1312;
export const ER_SP_BADRETURN = 1313;
export const ER_SP_BADSTATEMENT = 1314;
export const ER_UPDATE_LOG_DEPRECATED_IGNORED = 1315;
export const ER_UPDATE_LOG_DEPRECATED_TRANSLATED = 1316;
export const ER_QUERY_INTERRUPTED = 1317;
export const ER_SP_WRONG_NO_OF_ARGS = 1318;
export const ER_SP_COND_MISMATCH = 1319;
export const ER_SP_NORETURN = 1320;
export const ER_SP_NORETURNEND = 1321;
export const ER_SP_BAD_CURSOR_QUERY = 1322;
export const ER_SP_BAD_CURSOR_SELECT = 1323;
export const ER_SP_CURSOR_MISMATCH = 1324;
export const ER_SP_CURSOR_ALREADY_OPEN = 1325;
export const ER_SP_CURSOR_NOT_OPEN = 1326;
export const ER_SP_UNDECLARED_VAR = 1327;
export const ER_SP_WRONG_NO_OF_FETCH_ARGS = 1328;
export const ER_SP_FETCH_NO_DATA = 1329;
export const ER_SP_DUP_PARAM = 1330;
export const ER_SP_DUP_VAR = 1331;
export const ER_SP_DUP_COND = 1332;
export const ER_SP_DUP_CURS = 1333;
export const ER_SP_CANT_ALTER = 1334;
export const ER_SP_SUBSELECT_NYI = 1335;
export const ER_STMT_NOT_ALLOWED_IN_SF_OR_TRG = 1336;
export const ER_SP_VARCOND_AFTER_CURSHNDLR = 1337;
export const ER_SP_CURSOR_AFTER_HANDLER = 1338;
export const ER_SP_CASE_NOT_FOUND = 1339;
export const ER_FPARSER_TOO_BIG_FILE = 1340;
export const ER_FPARSER_BAD_HEADER = 1341;
export const ER_FPARSER_EOF_IN_COMMENT = 1342;
export const ER_FPARSER_ERROR_IN_PARAMETER = 1343;
export const ER_FPARSER_EOF_IN_UNKNOWN_PARAMETER = 1344;
export const ER_VIEW_NO_EXPLAIN = 1345;
export const ER_FRM_UNKNOWN_TYPE = 1346;
export const ER_WRONG_OBJECT = 1347;
export const ER_NONUPDATEABLE_COLUMN = 1348;
export const ER_VIEW_SELECT_DERIVED = 1349;
export const ER_VIEW_SELECT_CLAUSE = 1350;
export const ER_VIEW_SELECT_VARIABLE = 1351;
export const ER_VIEW_SELECT_TMPTABLE = 1352;
export const ER_VIEW_WRONG_LIST = 1353;
export const ER_WARN_VIEW_MERGE = 1354;
export const ER_WARN_VIEW_WITHOUT_KEY = 1355;
export const ER_VIEW_INVALID = 1356;
export const ER_SP_NO_DROP_SP = 1357;
export const ER_SP_GOTO_IN_HNDLR = 1358;
export const ER_TRG_ALREADY_EXISTS = 1359;
export const ER_TRG_DOES_NOT_EXIST = 1360;
export const ER_TRG_ON_VIEW_OR_TEMP_TABLE = 1361;
export const ER_TRG_CANT_CHANGE_ROW = 1362;
export const ER_TRG_NO_SUCH_ROW_IN_TRG = 1363;
export const ER_NO_DEFAULT_FOR_FIELD = 1364;
export const ER_DIVISION_BY_ZERO = 1365;
export const ER_TRUNCATED_WRONG_VALUE_FOR_FIELD = 1366;
export const ER_ILLEGAL_VALUE_FOR_TYPE = 1367;
export const ER_VIEW_NONUPD_CHECK = 1368;
export const ER_VIEW_CHECK_FAILED = 1369;
export const ER_PROCACCESS_DENIED_ERROR = 1370;
export const ER_RELAY_LOG_FAIL = 1371;
export const ER_PASSWD_LENGTH = 1372;
export const ER_UNKNOWN_TARGET_BINLOG = 1373;
export const ER_IO_ERR_LOG_INDEX_READ = 1374;
export const ER_BINLOG_PURGE_PROHIBITED = 1375;
export const ER_FSEEK_FAIL = 1376;
export const ER_BINLOG_PURGE_FATAL_ERR = 1377;
export const ER_LOG_IN_USE = 1378;
export const ER_LOG_PURGE_UNKNOWN_ERR = 1379;
export const ER_RELAY_LOG_INIT = 1380;
export const ER_NO_BINARY_LOGGING = 1381;
export const ER_RESERVED_SYNTAX = 1382;
export const ER_WSAS_FAILED = 1383;
export const ER_DIFF_GROUPS_PROC = 1384;
export const ER_NO_GROUP_FOR_PROC = 1385;
export const ER_ORDER_WITH_PROC = 1386;
export const ER_LOGGING_PROHIBIT_CHANGING_OF = 1387;
export const ER_NO_FILE_MAPPING = 1388;
export const ER_WRONG_MAGIC = 1389;
export const ER_PS_MANY_PARAM = 1390;
export const ER_KEY_PART_0 = 1391;
export const ER_VIEW_CHECKSUM = 1392;
export const ER_VIEW_MULTIUPDATE = 1393;
export const ER_VIEW_NO_INSERT_FIELD_LIST = 1394;
export const ER_VIEW_DELETE_MERGE_VIEW = 1395;
export const ER_CANNOT_USER = 1396;
export const ER_XAER_NOTA = 1397;
export const ER_XAER_INVAL = 1398;
export const ER_XAER_RMFAIL = 1399;
export const ER_XAER_OUTSIDE = 1400;
export const ER_XAER_RMERR = 1401;
export const ER_XA_RBROLLBACK = 1402;
export const ER_NONEXISTING_PROC_GRANT = 1403;
export const ER_PROC_AUTO_GRANT_FAIL = 1404;
export const ER_PROC_AUTO_REVOKE_FAIL = 1405;
export const ER_DATA_TOO_LONG = 1406;
export const ER_SP_BAD_SQLSTATE = 1407;
export const ER_STARTUP = 1408;
export const ER_LOAD_FROM_FIXED_SIZE_ROWS_TO_VAR = 1409;
export const ER_CANT_CREATE_USER_WITH_GRANT = 1410;
export const ER_WRONG_VALUE_FOR_TYPE = 1411;
export const ER_TABLE_DEF_CHANGED = 1412;
export const ER_SP_DUP_HANDLER = 1413;
export const ER_SP_NOT_VAR_ARG = 1414;
export const ER_SP_NO_RETSET = 1415;
export const ER_CANT_CREATE_GEOMETRY_OBJECT = 1416;
export const ER_FAILED_ROUTINE_BREAK_BINLOG = 1417;
export const ER_BINLOG_UNSAFE_ROUTINE = 1418;
export const ER_BINLOG_CREATE_ROUTINE_NEED_SUPER = 1419;
export const ER_EXEC_STMT_WITH_OPEN_CURSOR = 1420;
export const ER_STMT_HAS_NO_OPEN_CURSOR = 1421;
export const ER_COMMIT_NOT_ALLOWED_IN_SF_OR_TRG = 1422;
export const ER_NO_DEFAULT_FOR_VIEW_FIELD = 1423;
export const ER_SP_NO_RECURSION = 1424;
export const ER_TOO_BIG_SCALE = 1425;
export const ER_TOO_BIG_PRECISION = 1426;
export const ER_M_BIGGER_THAN_D = 1427;
export const ER_WRONG_LOCK_OF_SYSTEM_TABLE = 1428;
export const ER_CONNECT_TO_FOREIGN_DATA_SOURCE = 1429;
export const ER_QUERY_ON_FOREIGN_DATA_SOURCE = 1430;
export const ER_FOREIGN_DATA_SOURCE_DOESNT_EXIST = 1431;
export const ER_FOREIGN_DATA_STRING_INVALID_CANT_CREATE = 1432;
export const ER_FOREIGN_DATA_STRING_INVALID = 1433;
export const ER_CANT_CREATE_FEDERATED_TABLE = 1434;
export const ER_TRG_IN_WRONG_SCHEMA = 1435;
export const ER_STACK_OVERRUN_NEED_MORE = 1436;
export const ER_TOO_LONG_BODY = 1437;
export const ER_WARN_CANT_DROP_DEFAULT_KEYCACHE = 1438;
export const ER_TOO_BIG_DISPLAYWIDTH = 1439;
export const ER_XAER_DUPID = 1440;
export const ER_DATETIME_FUNCTION_OVERFLOW = 1441;
export const ER_CANT_UPDATE_USED_TABLE_IN_SF_OR_TRG = 1442;
export const ER_VIEW_PREVENT_UPDATE = 1443;
export const ER_PS_NO_RECURSION = 1444;
export const ER_SP_CANT_SET_AUTOCOMMIT = 1445;
export const ER_MALFORMED_DEFINER = 1446;
export const ER_VIEW_FRM_NO_USER = 1447;
export const ER_VIEW_OTHER_USER = 1448;
export const ER_NO_SUCH_USER = 1449;
export const ER_FORBID_SCHEMA_CHANGE = 1450;
export const ER_ROW_IS_REFERENCED_2 = 1451;
export const ER_NO_REFERENCED_ROW_2 = 1452;
export const ER_SP_BAD_VAR_SHADOW = 1453;
export const ER_TRG_NO_DEFINER = 1454;
export const ER_OLD_FILE_FORMAT = 1455;
export const ER_SP_RECURSION_LIMIT = 1456;
export const ER_SP_PROC_TABLE_CORRUPT = 1457;
export const ER_SP_WRONG_NAME = 1458;
export const ER_TABLE_NEEDS_UPGRADE = 1459;
export const ER_SP_NO_AGGREGATE = 1460;
export const ER_MAX_PREPARED_STMT_COUNT_REACHED = 1461;
export const ER_VIEW_RECURSIVE = 1462;
export const ER_NON_GROUPING_FIELD_USED = 1463;
export const ER_TABLE_CANT_HANDLE_SPKEYS = 1464;
export const ER_NO_TRIGGERS_ON_SYSTEM_SCHEMA = 1465;
export const ER_REMOVED_SPACES = 1466;
export const ER_AUTOINC_READ_FAILED = 1467;
export const ER_USERNAME = 1468;
export const ER_HOSTNAME = 1469;
export const ER_WRONG_STRING_LENGTH = 1470;
export const ER_NON_INSERTABLE_TABLE = 1471;
export const ER_ADMIN_WRONG_MRG_TABLE = 1472;
export const ER_TOO_HIGH_LEVEL_OF_NESTING_FOR_SELECT = 1473;
export const ER_NAME_BECOMES_EMPTY = 1474;
export const ER_AMBIGUOUS_FIELD_TERM = 1475;
export const ER_FOREIGN_SERVER_EXISTS = 1476;
export const ER_FOREIGN_SERVER_DOESNT_EXIST = 1477;
export const ER_ILLEGAL_HA_CREATE_OPTION = 1478;
export const ER_PARTITION_REQUIRES_VALUES_ERROR = 1479;
export const ER_PARTITION_WRONG_VALUES_ERROR = 1480;
export const ER_PARTITION_MAXVALUE_ERROR = 1481;
export const ER_PARTITION_SUBPARTITION_ERROR = 1482;
export const ER_PARTITION_SUBPART_MIX_ERROR = 1483;
export const ER_PARTITION_WRONG_NO_PART_ERROR = 1484;
export const ER_PARTITION_WRONG_NO_SUBPART_ERROR = 1485;
export const ER_WRONG_EXPR_IN_PARTITION_FUNC_ERROR = 1486;
export const ER_NO_CONST_EXPR_IN_RANGE_OR_LIST_ERROR = 1487;
export const ER_FIELD_NOT_FOUND_PART_ERROR = 1488;
export const ER_LIST_OF_FIELDS_ONLY_IN_HASH_ERROR = 1489;
export const ER_INCONSISTENT_PARTITION_INFO_ERROR = 1490;
export const ER_PARTITION_FUNC_NOT_ALLOWED_ERROR = 1491;
export const ER_PARTITIONS_MUST_BE_DEFINED_ERROR = 1492;
export const ER_RANGE_NOT_INCREASING_ERROR = 1493;
export const ER_INCONSISTENT_TYPE_OF_FUNCTIONS_ERROR = 1494;
export const ER_MULTIPLE_DEF_CONST_IN_LIST_PART_ERROR = 1495;
export const ER_PARTITION_ENTRY_ERROR = 1496;
export const ER_MIX_HANDLER_ERROR = 1497;
export const ER_PARTITION_NOT_DEFINED_ERROR = 1498;
export const ER_TOO_MANY_PARTITIONS_ERROR = 1499;
export const ER_SUBPARTITION_ERROR = 1500;
export const ER_CANT_CREATE_HANDLER_FILE = 1501;
export const ER_BLOB_FIELD_IN_PART_FUNC_ERROR = 1502;
export const ER_UNIQUE_KEY_NEED_ALL_FIELDS_IN_PF = 1503;
export const ER_NO_PARTS_ERROR = 1504;
export const ER_PARTITION_MGMT_ON_NONPARTITIONED = 1505;
export const ER_FOREIGN_KEY_ON_PARTITIONED = 1506;
export const ER_DROP_PARTITION_NON_EXISTENT = 1507;
export const ER_DROP_LAST_PARTITION = 1508;
export const ER_COALESCE_ONLY_ON_HASH_PARTITION = 1509;
export const ER_REORG_HASH_ONLY_ON_SAME_NO = 1510;
export const ER_REORG_NO_PARAM_ERROR = 1511;
export const ER_ONLY_ON_RANGE_LIST_PARTITION = 1512;
export const ER_ADD_PARTITION_SUBPART_ERROR = 1513;
export const ER_ADD_PARTITION_NO_NEW_PARTITION = 1514;
export const ER_COALESCE_PARTITION_NO_PARTITION = 1515;
export const ER_REORG_PARTITION_NOT_EXIST = 1516;
export const ER_SAME_NAME_PARTITION = 1517;
export const ER_NO_BINLOG_ERROR = 1518;
export const ER_CONSECUTIVE_REORG_PARTITIONS = 1519;
export const ER_REORG_OUTSIDE_RANGE = 1520;
export const ER_PARTITION_FUNCTION_FAILURE = 1521;
export const ER_PART_STATE_ERROR = 1522;
export const ER_LIMITED_PART_RANGE = 1523;
export const ER_PLUGIN_IS_NOT_LOADED = 1524;
export const ER_WRONG_VALUE = 1525;
export const ER_NO_PARTITION_FOR_GIVEN_VALUE = 1526;
export const ER_FILEGROUP_OPTION_ONLY_ONCE = 1527;
export const ER_CREATE_FILEGROUP_FAILED = 1528;
export const ER_DROP_FILEGROUP_FAILED = 1529;
export const ER_TABLESPACE_AUTO_EXTEND_ERROR = 1530;
export const ER_WRONG_SIZE_NUMBER = 1531;
export const ER_SIZE_OVERFLOW_ERROR = 1532;
export const ER_ALTER_FILEGROUP_FAILED = 1533;
export const ER_BINLOG_ROW_LOGGING_FAILED = 1534;
export const ER_BINLOG_ROW_WRONG_TABLE_DEF = 1535;
export const ER_BINLOG_ROW_RBR_TO_SBR = 1536;
export const ER_EVENT_ALREADY_EXISTS = 1537;
export const ER_EVENT_STORE_FAILED = 1538;
export const ER_EVENT_DOES_NOT_EXIST = 1539;
export const ER_EVENT_CANT_ALTER = 1540;
export const ER_EVENT_DROP_FAILED = 1541;
export const ER_EVENT_INTERVAL_NOT_POSITIVE_OR_TOO_BIG = 1542;
export const ER_EVENT_ENDS_BEFORE_STARTS = 1543;
export const ER_EVENT_EXEC_TIME_IN_THE_PAST = 1544;
export const ER_EVENT_OPEN_TABLE_FAILED = 1545;
export const ER_EVENT_NEITHER_M_EXPR_NOR_M_AT = 1546;
export const ER_COL_COUNT_DOESNT_MATCH_CORRUPTED = 1547;
export const ER_CANNOT_LOAD_FROM_TABLE = 1548;
export const ER_EVENT_CANNOT_DELETE = 1549;
export const ER_EVENT_COMPILE_ERROR = 1550;
export const ER_EVENT_SAME_NAME = 1551;
export const ER_EVENT_DATA_TOO_LONG = 1552;
export const ER_DROP_INDEX_FK = 1553;
export const ER_WARN_DEPRECATED_SYNTAX_WITH_VER = 1554;
export const ER_CANT_WRITE_LOCK_LOG_TABLE = 1555;
export const ER_CANT_LOCK_LOG_TABLE = 1556;
export const ER_FOREIGN_DUPLICATE_KEY = 1557;
export const ER_COL_COUNT_DOESNT_MATCH_PLEASE_UPDATE = 1558;
export const ER_TEMP_TABLE_PREVENTS_SWITCH_OUT_OF_RBR = 1559;
export const ER_STORED_FUNCTION_PREVENTS_SWITCH_BINLOG_FORMAT = 1560;
export const ER_NDB_CANT_SWITCH_BINLOG_FORMAT = 1561;
export const ER_PARTITION_NO_TEMPORARY = 1562;
export const ER_PARTITION_CONST_DOMAIN_ERROR = 1563;
export const ER_PARTITION_FUNCTION_IS_NOT_ALLOWED = 1564;
export const ER_DDL_LOG_ERROR = 1565;
export const ER_NULL_IN_VALUES_LESS_THAN = 1566;
export const ER_WRONG_PARTITION_NAME = 1567;
export const ER_CANT_CHANGE_TX_ISOLATION = 1568;
export const ER_DUP_ENTRY_AUTOINCREMENT_CASE = 1569;
export const ER_EVENT_MODIFY_QUEUE_ERROR = 1570;
export const ER_EVENT_SET_VAR_ERROR = 1571;
export const ER_PARTITION_MERGE_ERROR = 1572;
export const ER_CANT_ACTIVATE_LOG = 1573;
export const ER_RBR_NOT_AVAILABLE = 1574;
export const ER_BASE64_DECODE_ERROR = 1575;
export const ER_EVENT_RECURSION_FORBIDDEN = 1576;
export const ER_EVENTS_DB_ERROR = 1577;
export const ER_ONLY_INTEGERS_ALLOWED = 1578;
export const ER_UNSUPORTED_LOG_ENGINE = 1579;
export const ER_BAD_LOG_STATEMENT = 1580;
export const ER_CANT_RENAME_LOG_TABLE = 1581;
export const ER_WRONG_PARAMCOUNT_TO_NATIVE_FCT = 1582;
export const ER_WRONG_PARAMETERS_TO_NATIVE_FCT = 1583;
export const ER_WRONG_PARAMETERS_TO_STORED_FCT = 1584;
export const ER_NATIVE_FCT_NAME_COLLISION = 1585;
export const ER_DUP_ENTRY_WITH_KEY_NAME = 1586;
export const ER_BINLOG_PURGE_EMFILE = 1587;
export const ER_EVENT_CANNOT_CREATE_IN_THE_PAST = 1588;
export const ER_EVENT_CANNOT_ALTER_IN_THE_PAST = 1589;
export const ER_SLAVE_INCIDENT = 1590; // deprecated
export const ER_REPLICA_INCIDENT = 1590;
export const ER_NO_PARTITION_FOR_GIVEN_VALUE_SILENT = 1591;
export const ER_BINLOG_UNSAFE_STATEMENT = 1592;
export const ER_SLAVE_FATAL_ERROR = 1593; // deprecated
export const ER_REPLICA_FATAL_ERROR = 1593;
export const ER_SLAVE_RELAY_LOG_READ_FAILURE = 1594; //deprecated
export const ER_REPLICA_RELAY_LOG_READ_FAILURE = 1594;
export const ER_SLAVE_RELAY_LOG_WRITE_FAILURE = 1595; // deprecated
export const ER_REPLICA_RELAY_LOG_WRITE_FAILURE = 1595;
export const ER_SLAVE_CREATE_EVENT_FAILURE = 1596; // deprecated
export const ER_REPLICA_CREATE_EVENT_FAILURE = 1596;
export const ER_SLAVE_MASTER_COM_FAILURE = 1597; // deprecated
export const ER_REPLICA_SOURCE_COM_FAILURE = 1597;
export const ER_BINLOG_LOGGING_IMPOSSIBLE = 1598;
export const ER_VIEW_NO_CREATION_CTX = 1599;
export const ER_VIEW_INVALID_CREATION_CTX = 1600;
export const ER_SR_INVALID_CREATION_CTX = 1601;
export const ER_TRG_CORRUPTED_FILE = 1602;
export const ER_TRG_NO_CREATION_CTX = 1603;
export const ER_TRG_INVALID_CREATION_CTX = 1604;
export const ER_EVENT_INVALID_CREATION_CTX = 1605;
export const ER_TRG_CANT_OPEN_TABLE = 1606;
export const ER_CANT_CREATE_SROUTINE = 1607;
export const ER_NEVER_USED = 1608;
export const ER_NO_FORMAT_DESCRIPTION_EVENT_BEFORE_BINLOG_STATEMENT = 1609;
export const ER_SLAVE_CORRUPT_EVENT = 1610; // deprecated
export const ER_REPLICA_CORRUPT_EVENT = 1610;
export const ER_LOAD_DATA_INVALID_COLUMN = 1611;
export const ER_LOG_PURGE_NO_FILE = 1612;
export const ER_XA_RBTIMEOUT = 1613;
export const ER_XA_RBDEADLOCK = 1614;
export const ER_NEED_REPREPARE = 1615;
export const ER_DELAYED_NOT_SUPPORTED = 1616;
export const WARN_NO_MASTER_INFO = 1617; // deprecated
export const WARN_NO_SOURCE_INFO = 1617;
export const WARN_OPTION_IGNORED = 1618;
export const WARN_PLUGIN_DELETE_BUILTIN = 1619;
export const WARN_PLUGIN_BUSY = 1620;
export const ER_VARIABLE_IS_READONLY = 1621;
export const ER_WARN_ENGINE_TRANSACTION_ROLLBACK = 1622;
export const ER_SLAVE_HEARTBEAT_FAILURE = 1623; // deprecated
export const ER_REPLICA_HEARTBEAT_FAILURE = 1623;
export const ER_SLAVE_HEARTBEAT_VALUE_OUT_OF_RANGE = 1624; // deprecated
export const ER_REPLICA_HEARTBEAT_VALUE_OUT_OF_RANGE = 1624;
export const ER_NDB_REPLICATION_SCHEMA_ERROR = 1625;
export const ER_CONFLICT_FN_PARSE_ERROR = 1626;
export const ER_EXCEPTIONS_WRITE_ERROR = 1627;
export const ER_TOO_LONG_TABLE_COMMENT = 1628;
export const ER_TOO_LONG_FIELD_COMMENT = 1629;
export const ER_FUNC_INEXISTENT_NAME_COLLISION = 1630;
export const ER_DATABASE_NAME = 1631;
export const ER_TABLE_NAME = 1632;
export const ER_PARTITION_NAME = 1633;
export const ER_SUBPARTITION_NAME = 1634;
export const ER_TEMPORARY_NAME = 1635;
export const ER_RENAMED_NAME = 1636;
export const ER_TOO_MANY_CONCURRENT_TRXS = 1637;
export const WARN_NON_ASCII_SEPARATOR_NOT_IMPLEMENTED = 1638;
export const ER_DEBUG_SYNC_TIMEOUT = 1639;
export const ER_DEBUG_SYNC_HIT_LIMIT = 1640;
export const ER_DUP_SIGNAL_SET = 1641;
export const ER_SIGNAL_WARN = 1642;
export const ER_SIGNAL_NOT_FOUND = 1643;
export const ER_SIGNAL_EXCEPTION = 1644;
export const ER_RESIGNAL_WITHOUT_ACTIVE_HANDLER = 1645;
export const ER_SIGNAL_BAD_CONDITION_TYPE = 1646;
export const WARN_COND_ITEM_TRUNCATED = 1647;
export const ER_COND_ITEM_TOO_LONG = 1648;
export const ER_UNKNOWN_LOCALE = 1649;
export const ER_SLAVE_IGNORE_SERVER_IDS = 1650; // deprecated
export const ER_REPLICA_IGNORE_SERVER_IDS = 1650;
export const ER_QUERY_CACHE_DISABLED = 1651;
export const ER_SAME_NAME_PARTITION_FIELD = 1652;
export const ER_PARTITION_COLUMN_LIST_ERROR = 1653;
export const ER_WRONG_TYPE_COLUMN_VALUE_ERROR = 1654;
export const ER_TOO_MANY_PARTITION_FUNC_FIELDS_ERROR = 1655;
export const ER_MAXVALUE_IN_VALUES_IN = 1656;
export const ER_TOO_MANY_VALUES_ERROR = 1657;
export const ER_ROW_SINGLE_PARTITION_FIELD_ERROR = 1658;
export const ER_FIELD_TYPE_NOT_ALLOWED_AS_PARTITION_FIELD = 1659;
export const ER_PARTITION_FIELDS_TOO_LONG = 1660;
export const ER_BINLOG_ROW_ENGINE_AND_STMT_ENGINE = 1661;
export const ER_BINLOG_ROW_MODE_AND_STMT_ENGINE = 1662;
export const ER_BINLOG_UNSAFE_AND_STMT_ENGINE = 1663;
export const ER_BINLOG_ROW_INJECTION_AND_STMT_ENGINE = 1664;
export const ER_BINLOG_STMT_MODE_AND_ROW_ENGINE = 1665;
export const ER_BINLOG_ROW_INJECTION_AND_STMT_MODE = 1666;
export const ER_BINLOG_MULTIPLE_ENGINES_AND_SELF_LOGGING_ENGINE = 1667;
export const ER_BINLOG_UNSAFE_LIMIT = 1668;
export const ER_BINLOG_UNSAFE_INSERT_DELAYED = 1669;
export const ER_BINLOG_UNSAFE_SYSTEM_TABLE = 1670;
export const ER_BINLOG_UNSAFE_AUTOINC_COLUMNS = 1671;
export const ER_BINLOG_UNSAFE_UDF = 1672;
export const ER_BINLOG_UNSAFE_SYSTEM_VARIABLE = 1673;
export const ER_BINLOG_UNSAFE_SYSTEM_FUNCTION = 1674;
export const ER_BINLOG_UNSAFE_NONTRANS_AFTER_TRANS = 1675;
export const ER_MESSAGE_AND_STATEMENT = 1676;
export const ER_SLAVE_CONVERSION_FAILED = 1677; // deprecated
export const ER_REPLICA_CONVERSION_FAILED = 1677;
export const ER_SLAVE_CANT_CREATE_CONVERSION = 1678; // deprecated
export const ER_REPLICA_CANT_CREATE_CONVERSION = 1678;
export const ER_INSIDE_TRANSACTION_PREVENTS_SWITCH_BINLOG_FORMAT = 1679;
export const ER_PATH_LENGTH = 1680;
export const ER_WARN_DEPRECATED_SYNTAX_NO_REPLACEMENT = 1681;
export const ER_WRONG_NATIVE_TABLE_STRUCTURE = 1682;
export const ER_WRONG_PERFSCHEMA_USAGE = 1683;
export const ER_WARN_I_S_SKIPPED_TABLE = 1684;
export const ER_INSIDE_TRANSACTION_PREVENTS_SWITCH_BINLOG_DIRECT = 1685;
export const ER_STORED_FUNCTION_PREVENTS_SWITCH_BINLOG_DIRECT = 1686;
export const ER_SPATIAL_MUST_HAVE_GEOM_COL = 1687;
export const ER_TOO_LONG_INDEX_COMMENT = 1688;
export const ER_LOCK_ABORTED = 1689;
export const ER_DATA_OUT_OF_RANGE = 1690;
export const ER_WRONG_SPVAR_TYPE_IN_LIMIT = 1691;
export const ER_BINLOG_UNSAFE_MULTIPLE_ENGINES_AND_SELF_LOGGING_ENGINE = 1692;
export const ER_BINLOG_UNSAFE_MIXED_STATEMENT = 1693;
export const ER_INSIDE_TRANSACTION_PREVENTS_SWITCH_SQL_LOG_BIN = 1694;
export const ER_STORED_FUNCTION_PREVENTS_SWITCH_SQL_LOG_BIN = 1695;
export const ER_FAILED_READ_FROM_PAR_FILE = 1696;
export const ER_VALUES_IS_NOT_INT_TYPE_ERROR = 1697;
export const ER_ACCESS_DENIED_NO_PASSWORD_ERROR = 1698;
export const ER_SET_PASSWORD_AUTH_PLUGIN = 1699;
export const ER_GRANT_PLUGIN_USER_EXISTS = 1700;
export const ER_TRUNCATE_ILLEGAL_FK = 1701;
export const ER_PLUGIN_IS_PERMANENT = 1702;
export const ER_SLAVE_HEARTBEAT_VALUE_OUT_OF_RANGE_MIN = 1703; // deprecated
export const ER_REPLICA_HEARTBEAT_VALUE_OUT_OF_RANGE_MIN = 1703;
export const ER_SLAVE_HEARTBEAT_VALUE_OUT_OF_RANGE_MAX = 1704; // deprecated
export const ER_REPLICA_HEARTBEAT_VALUE_OUT_OF_RANGE_MAX = 1704;
export const ER_STMT_CACHE_FULL = 1705;
export const ER_MULTI_UPDATE_KEY_CONFLICT = 1706;
export const ER_TABLE_NEEDS_REBUILD = 1707;
export const WARN_OPTION_BELOW_LIMIT = 1708;
export const ER_INDEX_COLUMN_TOO_LONG = 1709;
export const ER_ERROR_IN_TRIGGER_BODY = 1710;
export const ER_ERROR_IN_UNKNOWN_TRIGGER_BODY = 1711;
export const ER_INDEX_CORRUPT = 1712;
export const ER_UNDO_RECORD_TOO_BIG = 1713;
export const ER_BINLOG_UNSAFE_INSERT_IGNORE_SELECT = 1714;
export const ER_BINLOG_UNSAFE_INSERT_SELECT_UPDATE = 1715;
export const ER_BINLOG_UNSAFE_REPLACE_SELECT = 1716;
export const ER_BINLOG_UNSAFE_CREATE_IGNORE_SELECT = 1717;
export const ER_BINLOG_UNSAFE_CREATE_REPLACE_SELECT = 1718;
export const ER_BINLOG_UNSAFE_UPDATE_IGNORE = 1719;
export const ER_PLUGIN_NO_UNINSTALL = 1720;
export const ER_PLUGIN_NO_INSTALL = 1721;
export const ER_BINLOG_UNSAFE_WRITE_AUTOINC_SELECT = 1722;
export const ER_BINLOG_UNSAFE_CREATE_SELECT_AUTOINC = 1723;
export const ER_BINLOG_UNSAFE_INSERT_TWO_KEYS = 1724;
export const ER_TABLE_IN_FK_CHECK = 1725;
export const ER_UNSUPPORTED_ENGINE = 1726;
export const ER_BINLOG_UNSAFE_AUTOINC_NOT_FIRST = 1727;
export const ER_CANNOT_LOAD_FROM_TABLE_V2 = 1728;
export const ER_MASTER_DELAY_VALUE_OUT_OF_RANGE = 1729; // deprecated
export const ER_SOURCE_DELAY_VALUE_OUT_OF_RANGE = 1729;
export const ER_ONLY_FD_AND_RBR_EVENTS_ALLOWED_IN_BINLOG_STATEMENT = 1730;
export const ER_PARTITION_EXCHANGE_DIFFERENT_OPTION = 1731;
export const ER_PARTITION_EXCHANGE_PART_TABLE = 1732;
export const ER_PARTITION_EXCHANGE_TEMP_TABLE = 1733;
export const ER_PARTITION_INSTEAD_OF_SUBPARTITION = 1734;
export const ER_UNKNOWN_PARTITION = 1735;
export const ER_TABLES_DIFFERENT_METADATA = 1736;
export const ER_ROW_DOES_NOT_MATCH_PARTITION = 1737;
export const ER_BINLOG_CACHE_SIZE_GREATER_THAN_MAX = 1738;
export const ER_WARN_INDEX_NOT_APPLICABLE = 1739;
export const ER_PARTITION_EXCHANGE_FOREIGN_KEY = 1740;
export const ER_NO_SUCH_KEY_VALUE = 1741;
export const ER_RPL_INFO_DATA_TOO_LONG = 1742;
export const ER_NETWORK_READ_EVENT_CHECKSUM_FAILURE = 1743;
export const ER_BINLOG_READ_EVENT_CHECKSUM_FAILURE = 1744;
export const ER_BINLOG_STMT_CACHE_SIZE_GREATER_THAN_MAX = 1745;
export const ER_CANT_UPDATE_TABLE_IN_CREATE_TABLE_SELECT = 1746;
export const ER_PARTITION_CLAUSE_ON_NONPARTITIONED = 1747;
export const ER_ROW_DOES_NOT_MATCH_GIVEN_PARTITION_SET = 1748;
export const ER_NO_SUCH_PARTITION = 1749;
export const ER_CHANGE_RPL_INFO_REPOSITORY_FAILURE = 1750;
export const ER_WARNING_NOT_COMPLETE_ROLLBACK_WITH_CREATED_TEMP_TABLE = 1751;
export const ER_WARNING_NOT_COMPLETE_ROLLBACK_WITH_DROPPED_TEMP_TABLE = 1752;
export const ER_MTS_FEATURE_IS_NOT_SUPPORTED = 1753;
export const ER_MTS_UPDATED_DBS_GREATER_MAX = 1754;
export const ER_MTS_CANT_PARALLEL = 1755;
export const ER_MTS_INCONSISTENT_DATA = 1756;
export const ER_FULLTEXT_NOT_SUPPORTED_WITH_PARTITIONING = 1757;
export const ER_DA_INVALID_CONDITION_NUMBER = 1758;
export const ER_INSECURE_PLAIN_TEXT = 1759;
export const ER_INSECURE_CHANGE_MASTER = 1760; // deprecated
export const ER_INSECURE_CHANGE_SOURCE = 1760;
export const ER_FOREIGN_DUPLICATE_KEY_WITH_CHILD_INFO = 1761;
export const ER_FOREIGN_DUPLICATE_KEY_WITHOUT_CHILD_INFO = 1762;
export const ER_SQLTHREAD_WITH_SECURE_SLAVE = 1763; // deprecated
export const ER_SQLTHREAD_WITH_SECURE_REPLICA = 1763;
export const ER_TABLE_HAS_NO_FT = 1764;
export const ER_VARIABLE_NOT_SETTABLE_IN_SF_OR_TRIGGER = 1765;
export const ER_VARIABLE_NOT_SETTABLE_IN_TRANSACTION = 1766;
export const ER_GTID_NEXT_IS_NOT_IN_GTID_NEXT_LIST = 1767;
export const ER_CANT_CHANGE_GTID_NEXT_IN_TRANSACTION_WHEN_GTID_NEXT_LIST_IS_NULL = 1768;
export const ER_SET_STATEMENT_CANNOT_INVOKE_FUNCTION = 1769;
export const ER_GTID_NEXT_CANT_BE_AUTOMATIC_IF_GTID_NEXT_LIST_IS_NON_NULL = 1770;
export const ER_SKIPPING_LOGGED_TRANSACTION = 1771;
export const ER_MALFORMED_GTID_SET_SPECIFICATION = 1772;
export const ER_MALFORMED_GTID_SET_ENCODING = 1773;
export const ER_MALFORMED_GTID_SPECIFICATION = 1774;
export const ER_GNO_EXHAUSTED = 1775;
export const ER_BAD_SLAVE_AUTO_POSITION = 1776; // deprecated
export const ER_BAD_REPLICA_AUTO_POSITION = 1776;
export const ER_AUTO_POSITION_REQUIRES_GTID_MODE_ON = 1777;
export const ER_CANT_DO_IMPLICIT_COMMIT_IN_TRX_WHEN_GTID_NEXT_IS_SET = 1778;
export const ER_GTID_MODE_2_OR_3_REQUIRES_ENFORCE_GTID_CONSISTENCY_ON = 1779;
export const ER_GTID_MODE_REQUIRES_BINLOG = 1780;
export const ER_CANT_SET_GTID_NEXT_TO_GTID_WHEN_GTID_MODE_IS_OFF = 1781;
export const ER_CANT_SET_GTID_NEXT_TO_ANONYMOUS_WHEN_GTID_MODE_IS_ON = 1782;
export const ER_CANT_SET_GTID_NEXT_LIST_TO_NON_NULL_WHEN_GTID_MODE_IS_OFF = 1783;
export const ER_FOUND_GTID_EVENT_WHEN_GTID_MODE_IS_OFF = 1784;
export const ER_GTID_UNSAFE_NON_TRANSACTIONAL_TABLE = 1785;
export const ER_GTID_UNSAFE_CREATE_SELECT = 1786;
export const ER_GTID_UNSAFE_CREATE_DROP_TEMPORARY_TABLE_IN_TRANSACTION = 1787;
export const ER_GTID_MODE_CAN_ONLY_CHANGE_ONE_STEP_AT_A_TIME = 1788;
export const ER_MASTER_HAS_PURGED_REQUIRED_GTIDS = 1789; // deprecated
export const ER_SOURCE_HAS_PURGED_REQUIRED_GTIDS = 1789;
export const ER_CANT_SET_GTID_NEXT_WHEN_OWNING_GTID = 1790;
export const ER_UNKNOWN_EXPLAIN_FORMAT = 1791;
export const ER_CANT_EXECUTE_IN_READ_ONLY_TRANSACTION = 1792;
export const ER_TOO_LONG_TABLE_PARTITION_COMMENT = 1793;
export const ER_SLAVE_CONFIGURATION = 1794; // deprecated
export const ER_REPLICA_CONFIGURATION = 1794;
export const ER_INNODB_FT_LIMIT = 1795;
export const ER_INNODB_NO_FT_TEMP_TABLE = 1796;
export const ER_INNODB_FT_WRONG_DOCID_COLUMN = 1797;
export const ER_INNODB_FT_WRONG_DOCID_INDEX = 1798;
export const ER_INNODB_ONLINE_LOG_TOO_BIG = 1799;
export const ER_UNKNOWN_ALTER_ALGORITHM = 1800;
export const ER_UNKNOWN_ALTER_LOCK = 1801;
export const ER_MTS_CHANGE_MASTER_CANT_RUN_WITH_GAPS = 1802; // deprecated
export const ER_MTS_CHANGE_SOURCE_CANT_RUN_WITH_GAPS = 1802;
export const ER_MTS_RECOVERY_FAILURE = 1803;
export const ER_MTS_RESET_WORKERS = 1804;
export const ER_COL_COUNT_DOESNT_MATCH_CORRUPTED_V2 = 1805;
export const ER_SLAVE_SILENT_RETRY_TRANSACTION = 1806; // deprecated
export const ER_REPLICA_SILENT_RETRY_TRANSACTION = 1806;
export const ER_DISCARD_FK_CHECKS_RUNNING = 1807;
export const ER_TABLE_SCHEMA_MISMATCH = 1808;
export const ER_TABLE_IN_SYSTEM_TABLESPACE = 1809;
export const ER_IO_READ_ERROR = 1810;
export const ER_IO_WRITE_ERROR = 1811;
export const ER_TABLESPACE_MISSING = 1812;
export const ER_TABLESPACE_EXISTS = 1813;
export const ER_TABLESPACE_DISCARDED = 1814;
export const ER_INTERNAL_ERROR = 1815;
export const ER_INNODB_IMPORT_ERROR = 1816;
export const ER_INNODB_INDEX_CORRUPT = 1817;
export const ER_INVALID_YEAR_COLUMN_LENGTH = 1818;
export const ER_NOT_VALID_PASSWORD = 1819;
export const ER_MUST_CHANGE_PASSWORD = 1820;
export const ER_FK_NO_INDEX_CHILD = 1821;
export const ER_FK_NO_INDEX_PARENT = 1822;
export const ER_FK_FAIL_ADD_SYSTEM = 1823;
export const ER_FK_CANNOT_OPEN_PARENT = 1824;
export const ER_FK_INCORRECT_OPTION = 1825;
export const ER_FK_DUP_NAME = 1826;
export const ER_PASSWORD_FORMAT = 1827;
export const ER_FK_COLUMN_CANNOT_DROP = 1828;
export const ER_FK_COLUMN_CANNOT_DROP_CHILD = 1829;
export const ER_FK_COLUMN_NOT_NULL = 1830;
export const ER_DUP_INDEX = 1831;
export const ER_FK_COLUMN_CANNOT_CHANGE = 1832;
export const ER_FK_COLUMN_CANNOT_CHANGE_CHILD = 1833;
export const ER_FK_CANNOT_DELETE_PARENT = 1834;
export const ER_MALFORMED_PACKET = 1835;
export const ER_READ_ONLY_MODE = 1836;
export const ER_GTID_NEXT_TYPE_UNDEFINED_GROUP = 1837;
export const ER_VARIABLE_NOT_SETTABLE_IN_SP = 1838;
export const ER_CANT_SET_GTID_PURGED_WHEN_GTID_MODE_IS_OFF = 1839;
export const ER_CANT_SET_GTID_PURGED_WHEN_GTID_EXECUTED_IS_NOT_EMPTY = 1840;
export const ER_CANT_SET_GTID_PURGED_WHEN_OWNED_GTIDS_IS_NOT_EMPTY = 1841;
export const ER_GTID_PURGED_WAS_CHANGED = 1842;
export const ER_GTID_EXECUTED_WAS_CHANGED = 1843;
export const ER_BINLOG_STMT_MODE_AND_NO_REPL_TABLES = 1844;
export const ER_ALTER_OPERATION_NOT_SUPPORTED = 1845;
export const ER_ALTER_OPERATION_NOT_SUPPORTED_REASON = 1846;
export const ER_ALTER_OPERATION_NOT_SUPPORTED_REASON_COPY = 1847;
export const ER_ALTER_OPERATION_NOT_SUPPORTED_REASON_PARTITION = 1848;
export const ER_ALTER_OPERATION_NOT_SUPPORTED_REASON_FK_RENAME = 1849;
export const ER_ALTER_OPERATION_NOT_SUPPORTED_REASON_COLUMN_TYPE = 1850;
export const ER_ALTER_OPERATION_NOT_SUPPORTED_REASON_FK_CHECK = 1851;
export const ER_ALTER_OPERATION_NOT_SUPPORTED_REASON_IGNORE = 1852;
export const ER_ALTER_OPERATION_NOT_SUPPORTED_REASON_NOPK = 1853;
export const ER_ALTER_OPERATION_NOT_SUPPORTED_REASON_AUTOINC = 1854;
export const ER_ALTER_OPERATION_NOT_SUPPORTED_REASON_HIDDEN_FTS = 1855;
export const ER_ALTER_OPERATION_NOT_SUPPORTED_REASON_CHANGE_FTS = 1856;
export const ER_ALTER_OPERATION_NOT_SUPPORTED_REASON_FTS = 1857;
export const ER_SQL_SLAVE_SKIP_COUNTER_NOT_SETTABLE_IN_GTID_MODE = 1858; // deprecated
export const ER_SQL_REPLICA_SKIP_COUNTER_NOT_SETTABLE_IN_GTID_MODE = 1858;
export const ER_DUP_UNKNOWN_IN_INDEX = 1859;
export const ER_IDENT_CAUSES_TOO_LONG_PATH = 1860;
export const ER_ALTER_OPERATION_NOT_SUPPORTED_REASON_NOT_NULL = 1861;
export const ER_MUST_CHANGE_PASSWORD_LOGIN = 1862;
export const ER_ROW_IN_WRONG_PARTITION = 1863;
export const ER_MTS_EVENT_BIGGER_PENDING_JOBS_SIZE_MAX = 1864;
export const ER_INNODB_NO_FT_USES_PARSER = 1865;
export const ER_BINLOG_LOGICAL_CORRUPTION = 1866;
export const ER_WARN_PURGE_LOG_IN_USE = 1867;
export const ER_WARN_PURGE_LOG_IS_ACTIVE = 1868;
export const ER_AUTO_INCREMENT_CONFLICT = 1869;
export const WARN_ON_BLOCKHOLE_IN_RBR = 1870;
export const ER_SLAVE_MI_INIT_REPOSITORY = 1871; // deprecated
export const ER_REPLICA_MI_INIT_REPOSITORY = 1871;
export const ER_SLAVE_RLI_INIT_REPOSITORY = 1872; // deprecated
export const ER_REPLICA_RLI_INIT_REPOSITORY = 1872;
export const ER_ACCESS_DENIED_CHANGE_USER_ERROR = 1873;
export const ER_INNODB_READ_ONLY = 1874;
export const ER_STOP_SLAVE_SQL_THREAD_TIMEOUT = 1875; // deprecated
export const ER_STOP_REPLICA_SQL_THREAD_TIMEOUT = 1875;
export const ER_STOP_SLAVE_IO_THREAD_TIMEOUT = 1876; // deprecated
export const ER_STOP_REPLICA_IO_THREAD_TIMEOUT = 1876;
export const ER_TABLE_CORRUPT = 1877;
export const ER_TEMP_FILE_WRITE_FAILURE = 1878;
export const ER_INNODB_FT_AUX_NOT_HEX_ID = 1879;
export const ER_OLD_TEMPORALS_UPGRADED = 1880;
export const ER_INNODB_FORCED_RECOVERY = 1881;
export const ER_AES_INVALID_IV = 1882;
export const ER_FILE_CORRUPT = 1883;
export const ER_ERROR_ON_SOURCE = 1884;
export const ER_INCONSISTENT_ERROR = 1885;
export const ER_STORAGE_ENGINE_NOT_LOADED = 1886;
export const ER_GET_STACKED_DA_WITHOUT_ACTIVE_HANDLER = 1887;
export const ER_WARN_LEGACY_SYNTAX_CONVERTED = 1888;
export const ER_BINLOG_UNSAFE_FULLTEXT_PLUGIN = 1889;
export const ER_CANNOT_DISCARD_TEMPORARY_TABLE = 1890;
export const ER_FK_DEPTH_EXCEEDED = 1891;
export const ER_COL_COUNT_DOESNT_MATCH_PLEASE_UPDATE_V2 = 1892;
export const ER_WARN_TRIGGER_DOESNT_HAVE_CREATED = 1893;
export const ER_REFERENCED_TRG_DOES_NOT_EXIST = 1894;
export const ER_EXPLAIN_NOT_SUPPORTED = 1895;
export const ER_INVALID_FIELD_SIZE = 1896;
export const ER_MISSING_HA_CREATE_OPTION = 1897;
export const ER_ENGINE_OUT_OF_MEMORY = 1898;
export const ER_PASSWORD_EXPIRE_ANONYMOUS_USER = 1899;
export const ER_REPLICA_SQL_THREAD_MUST_STOP = 1900;
export const ER_NO_FT_MATERIALIZED_SUBQUERY = 1901;
export const ER_INNODB_UNDO_LOG_FULL = 1902;
export const ER_INVALID_ARGUMENT_FOR_LOGARITHM = 1903;
export const ER_REPLICA_IO_THREAD_MUST_STOP = 1904;
export const ER_WARN_OPEN_TEMP_TABLES_MUST_BE_ZERO = 1905;
export const ER_WARN_ONLY_SOURCE_LOG_FILE_NO_POS = 1906;
export const ER_QUERY_TIMEOUT = 1907;
export const ER_NON_RO_SELECT_DISABLE_TIMER = 1908;
export const ER_DUP_LIST_ENTRY = 1909;
export const ER_SQL_MODE_NO_EFFECT = 1910;
export const ER_SESSION_WAS_KILLED = 3169;
export const ER_CLIENT_INTERACTION_TIMEOUT = 4031;

export const ErrorCodeById: Record<number, string> = {
  1: 'EE_CANTCREATEFILE',
  2: 'EE_READ',
  3: 'EE_WRITE',
  4: 'EE_BADCLOSE',
  5: 'EE_OUTOFMEMORY',
  6: 'EE_DELETE',
  7: 'EE_LINK',
  9: 'EE_EOFERR',
  10: 'EE_CANTLOCK',
  11: 'EE_CANTUNLOCK',
  12: 'EE_DIR',
  13: 'EE_STAT',
  14: 'EE_CANT_CHSIZE',
  15: 'EE_CANT_OPEN_STREAM',
  16: 'EE_GETWD',
  17: 'EE_SETWD',
  18: 'EE_LINK_WARNING',
  19: 'EE_OPEN_WARNING',
  20: 'EE_DISK_FULL',
  21: 'EE_CANT_MKDIR',
  22: 'EE_UNKNOWN_CHARSET',
  23: 'EE_OUT_OF_FILERESOURCES',
  24: 'EE_CANT_READLINK',
  25: 'EE_CANT_SYMLINK',
  26: 'EE_REALPATH',
  27: 'EE_SYNC',
  28: 'EE_UNKNOWN_COLLATION',
  29: 'EE_FILENOTFOUND',
  30: 'EE_FILE_NOT_CLOSED',
  31: 'EE_CHANGE_OWNERSHIP',
  32: 'EE_CHANGE_PERMISSIONS',
  33: 'EE_CANT_SEEK',
  120: 'HA_ERR_KEY_NOT_FOUND',
  121: 'HA_ERR_FOUND_DUPP_KEY',
  122: 'HA_ERR_INTERNAL_ERROR',
  123: 'HA_ERR_RECORD_CHANGED',
  124: 'HA_ERR_WRONG_INDEX',
  126: 'HA_ERR_CRASHED',
  127: 'HA_ERR_WRONG_IN_RECORD',
  128: 'HA_ERR_OUT_OF_MEM',
  130: 'HA_ERR_NOT_A_TABLE',
  131: 'HA_ERR_WRONG_COMMAND',
  132: 'HA_ERR_OLD_FILE',
  133: 'HA_ERR_NO_ACTIVE_RECORD',
  134: 'HA_ERR_RECORD_DELETED',
  135: 'HA_ERR_RECORD_FILE_FULL',
  136: 'HA_ERR_INDEX_FILE_FULL',
  137: 'HA_ERR_END_OF_FILE',
  138: 'HA_ERR_UNSUPPORTED',
  139: 'HA_ERR_TO_BIG_ROW',
  140: 'HA_WRONG_CREATE_OPTION',
  141: 'HA_ERR_FOUND_DUPP_UNIQUE',
  142: 'HA_ERR_UNKNOWN_CHARSET',
  143: 'HA_ERR_WRONG_MRG_TABLE_DEF',
  144: 'HA_ERR_CRASHED_ON_REPAIR',
  145: 'HA_ERR_CRASHED_ON_USAGE',
  146: 'HA_ERR_LOCK_WAIT_TIMEOUT',
  147: 'HA_ERR_LOCK_TABLE_FULL',
  148: 'HA_ERR_READ_ONLY_TRANSACTION',
  149: 'HA_ERR_LOCK_DEADLOCK',
  150: 'HA_ERR_CANNOT_ADD_FOREIGN',
  151: 'HA_ERR_NO_REFERENCED_ROW',
  152: 'HA_ERR_ROW_IS_REFERENCED',
  153: 'HA_ERR_NO_SAVEPOINT',
  154: 'HA_ERR_NON_UNIQUE_BLOCK_SIZE',
  155: 'HA_ERR_NO_SUCH_TABLE',
  156: 'HA_ERR_TABLE_EXIST',
  157: 'HA_ERR_NO_CONNECTION',
  158: 'HA_ERR_NULL_IN_SPATIAL',
  159: 'HA_ERR_TABLE_DEF_CHANGED',
  160: 'HA_ERR_NO_PARTITION_FOUND',
  161: 'HA_ERR_RBR_LOGGING_FAILED',
  162: 'HA_ERR_DROP_INDEX_FK',
  163: 'HA_ERR_FOREIGN_DUPLICATE_KEY',
  164: 'HA_ERR_TABLE_NEEDS_UPGRADE',
  165: 'HA_ERR_TABLE_READONLY',
  166: 'HA_ERR_AUTOINC_READ_FAILED',
  167: 'HA_ERR_AUTOINC_ERANGE',
  168: 'HA_ERR_GENERIC',
  169: 'HA_ERR_RECORD_IS_THE_SAME',
  170: 'HA_ERR_LOGGING_IMPOSSIBLE',
  171: 'HA_ERR_CORRUPT_EVENT',
  172: 'HA_ERR_NEW_FILE',
  173: 'HA_ERR_ROWS_EVENT_APPLY',
  174: 'HA_ERR_INITIALIZATION',
  175: 'HA_ERR_FILE_TOO_SHORT',
  176: 'HA_ERR_WRONG_CRC',
  177: 'HA_ERR_TOO_MANY_CONCURRENT_TRXS',
  178: 'HA_ERR_NOT_IN_LOCK_PARTITIONS',
  179: 'HA_ERR_INDEX_COL_TOO_LONG',
  180: 'HA_ERR_INDEX_CORRUPT',
  181: 'HA_ERR_UNDO_REC_TOO_BIG',
  182: 'HA_FTS_INVALID_DOCID',
  183: 'HA_ERR_TABLE_IN_FK_CHECK',
  184: 'HA_ERR_TABLESPACE_EXISTS',
  185: 'HA_ERR_TOO_MANY_FIELDS',
  186: 'HA_ERR_ROW_IN_WRONG_PARTITION',
  187: 'HA_ERR_INNODB_READ_ONLY',
  188: 'HA_ERR_FTS_EXCEED_RESULT_CACHE_LIMIT',
  189: 'HA_ERR_TEMP_FILE_WRITE_FAILURE',
  190: 'HA_ERR_INNODB_FORCED_RECOVERY',
  191: 'HA_ERR_FTS_TOO_MANY_WORDS_IN_PHRASE',
  1000: 'ER_HASHCHK',
  1001: 'ER_NISAMCHK',
  1002: 'ER_NO',
  1003: 'ER_YES',
  1004: 'ER_CANT_CREATE_FILE',
  1005: 'ER_CANT_CREATE_TABLE',
  1006: 'ER_CANT_CREATE_DB',
  1007: 'ER_DB_CREATE_EXISTS',
  1008: 'ER_DB_DROP_EXISTS',
  1009: 'ER_DB_DROP_DELETE',
  1010: 'ER_DB_DROP_RMDIR',
  1011: 'ER_CANT_DELETE_FILE',
  1012: 'ER_CANT_FIND_SYSTEM_REC',
  1013: 'ER_CANT_GET_STAT',
  1014: 'ER_CANT_GET_WD',
  1015: 'ER_CANT_LOCK',
  1016: 'ER_CANT_OPEN_FILE',
  1017: 'ER_FILE_NOT_FOUND',
  1018: 'ER_CANT_READ_DIR',
  1019: 'ER_CANT_SET_WD',
  1020: 'ER_CHECKREAD',
  1021: 'ER_DISK_FULL',
  1022: 'ER_DUP_KEY',
  1023: 'ER_ERROR_ON_CLOSE',
  1024: 'ER_ERROR_ON_READ',
  1025: 'ER_ERROR_ON_RENAME',
  1026: 'ER_ERROR_ON_WRITE',
  1027: 'ER_FILE_USED',
  1028: 'ER_FILSORT_ABORT',
  1029: 'ER_FORM_NOT_FOUND',
  1030: 'ER_GET_ERRNO',
  1031: 'ER_ILLEGAL_HA',
  1032: 'ER_KEY_NOT_FOUND',
  1033: 'ER_NOT_FORM_FILE',
  1034: 'ER_NOT_KEYFILE',
  1035: 'ER_OLD_KEYFILE',
  1036: 'ER_OPEN_AS_READONLY',
  1037: 'ER_OUTOFMEMORY',
  1038: 'ER_OUT_OF_SORTMEMORY',
  1039: 'ER_UNEXPECTED_EOF',
  1040: 'ER_CON_COUNT_ERROR',
  1041: 'ER_OUT_OF_RESOURCES',
  1042: 'ER_BAD_HOST_ERROR',
  1043: 'ER_HANDSHAKE_ERROR',
  1044: 'ER_DBACCESS_DENIED_ERROR',
  1045: 'ER_ACCESS_DENIED_ERROR',
  1046: 'ER_NO_DB_ERROR',
  1047: 'ER_UNKNOWN_COM_ERROR',
  1048: 'ER_BAD_NULL_ERROR',
  1049: 'ER_BAD_DB_ERROR',
  1050: 'ER_TABLE_EXISTS_ERROR',
  1051: 'ER_BAD_TABLE_ERROR',
  1052: 'ER_NON_UNIQ_ERROR',
  1053: 'ER_SERVER_SHUTDOWN',
  1054: 'ER_BAD_FIELD_ERROR',
  1055: 'ER_WRONG_FIELD_WITH_GROUP',
  1056: 'ER_WRONG_GROUP_FIELD',
  1057: 'ER_WRONG_SUM_SELECT',
  1058: 'ER_WRONG_VALUE_COUNT',
  1059: 'ER_TOO_LONG_IDENT',
  1060: 'ER_DUP_FIELDNAME',
  1061: 'ER_DUP_KEYNAME',
  1062: 'ER_DUP_ENTRY',
  1063: 'ER_WRONG_FIELD_SPEC',
  1064: 'ER_PARSE_ERROR',
  1065: 'ER_EMPTY_QUERY',
  1066: 'ER_NONUNIQ_TABLE',
  1067: 'ER_INVALID_DEFAULT',
  1068: 'ER_MULTIPLE_PRI_KEY',
  1069: 'ER_TOO_MANY_KEYS',
  1070: 'ER_TOO_MANY_KEY_PARTS',
  1071: 'ER_TOO_LONG_KEY',
  1072: 'ER_KEY_COLUMN_DOES_NOT_EXITS',
  1073: 'ER_BLOB_USED_AS_KEY',
  1074: 'ER_TOO_BIG_FIELDLENGTH',
  1075: 'ER_WRONG_AUTO_KEY',
  1076: 'ER_READY',
  1077: 'ER_NORMAL_SHUTDOWN',
  1078: 'ER_GOT_SIGNAL',
  1079: 'ER_SHUTDOWN_COMPLETE',
  1080: 'ER_FORCING_CLOSE',
  1081: 'ER_IPSOCK_ERROR',
  1082: 'ER_NO_SUCH_INDEX',
  1083: 'ER_WRONG_FIELD_TERMINATORS',
  1084: 'ER_BLOBS_AND_NO_TERMINATED',
  1085: 'ER_TEXTFILE_NOT_READABLE',
  1086: 'ER_FILE_EXISTS_ERROR',
  1087: 'ER_LOAD_INFO',
  1088: 'ER_ALTER_INFO',
  1089: 'ER_WRONG_SUB_KEY',
  1090: 'ER_CANT_REMOVE_ALL_FIELDS',
  1091: 'ER_CANT_DROP_FIELD_OR_KEY',
  1092: 'ER_INSERT_INFO',
  1093: 'ER_UPDATE_TABLE_USED',
  1094: 'ER_NO_SUCH_THREAD',
  1095: 'ER_KILL_DENIED_ERROR',
  1096: 'ER_NO_TABLES_USED',
  1097: 'ER_TOO_BIG_SET',
  1098: 'ER_NO_UNIQUE_LOGFILE',
  1099: 'ER_TABLE_NOT_LOCKED_FOR_WRITE',
  1100: 'ER_TABLE_NOT_LOCKED',
  1101: 'ER_BLOB_CANT_HAVE_DEFAULT',
  1102: 'ER_WRONG_DB_NAME',
  1103: 'ER_WRONG_TABLE_NAME',
  1104: 'ER_TOO_BIG_SELECT',
  1105: 'ER_UNKNOWN_ERROR',
  1106: 'ER_UNKNOWN_PROCEDURE',
  1107: 'ER_WRONG_PARAMCOUNT_TO_PROCEDURE',
  1108: 'ER_WRONG_PARAMETERS_TO_PROCEDURE',
  1109: 'ER_UNKNOWN_TABLE',
  1110: 'ER_FIELD_SPECIFIED_TWICE',
  1111: 'ER_INVALID_GROUP_FUNC_USE',
  1112: 'ER_UNSUPPORTED_EXTENSION',
  1113: 'ER_TABLE_MUST_HAVE_COLUMNS',
  1114: 'ER_RECORD_FILE_FULL',
  1115: 'ER_UNKNOWN_CHARACTER_SET',
  1116: 'ER_TOO_MANY_TABLES',
  1117: 'ER_TOO_MANY_FIELDS',
  1118: 'ER_TOO_BIG_ROWSIZE',
  1119: 'ER_STACK_OVERRUN',
  1120: 'ER_WRONG_OUTER_JOIN',
  1121: 'ER_NULL_COLUMN_IN_INDEX',
  1122: 'ER_CANT_FIND_UDF',
  1123: 'ER_CANT_INITIALIZE_UDF',
  1124: 'ER_UDF_NO_PATHS',
  1125: 'ER_UDF_EXISTS',
  1126: 'ER_CANT_OPEN_LIBRARY',
  1127: 'ER_CANT_FIND_DL_ENTRY',
  1128: 'ER_FUNCTION_NOT_DEFINED',
  1129: 'ER_HOST_IS_BLOCKED',
  1130: 'ER_HOST_NOT_PRIVILEGED',
  1131: 'ER_PASSWORD_ANONYMOUS_USER',
  1132: 'ER_PASSWORD_NOT_ALLOWED',
  1133: 'ER_PASSWORD_NO_MATCH',
  1134: 'ER_UPDATE_INFO',
  1135: 'ER_CANT_CREATE_THREAD',
  1136: 'ER_WRONG_VALUE_COUNT_ON_ROW',
  1137: 'ER_CANT_REOPEN_TABLE',
  1138: 'ER_INVALID_USE_OF_NULL',
  1139: 'ER_REGEXP_ERROR',
  1140: 'ER_MIX_OF_GROUP_FUNC_AND_FIELDS',
  1141: 'ER_NONEXISTING_GRANT',
  1142: 'ER_TABLEACCESS_DENIED_ERROR',
  1143: 'ER_COLUMNACCESS_DENIED_ERROR',
  1144: 'ER_ILLEGAL_GRANT_FOR_TABLE',
  1145: 'ER_GRANT_WRONG_HOST_OR_USER',
  1146: 'ER_NO_SUCH_TABLE',
  1147: 'ER_NONEXISTING_TABLE_GRANT',
  1148: 'ER_NOT_ALLOWED_COMMAND',
  1149: 'ER_SYNTAX_ERROR',
  1150: 'ER_DELAYED_CANT_CHANGE_LOCK',
  1151: 'ER_TOO_MANY_DELAYED_THREADS',
  1152: 'ER_ABORTING_CONNECTION',
  1153: 'ER_NET_PACKET_TOO_LARGE',
  1154: 'ER_NET_READ_ERROR_FROM_PIPE',
  1155: 'ER_NET_FCNTL_ERROR',
  1156: 'ER_NET_PACKETS_OUT_OF_ORDER',
  1157: 'ER_NET_UNCOMPRESS_ERROR',
  1158: 'ER_NET_READ_ERROR',
  1159: 'ER_NET_READ_INTERRUPTED',
  1160: 'ER_NET_ERROR_ON_WRITE',
  1161: 'ER_NET_WRITE_INTERRUPTED',
  1162: 'ER_TOO_LONG_STRING',
  1163: 'ER_TABLE_CANT_HANDLE_BLOB',
  1164: 'ER_TABLE_CANT_HANDLE_AUTO_INCREMENT',
  1165: 'ER_DELAYED_INSERT_TABLE_LOCKED',
  1166: 'ER_WRONG_COLUMN_NAME',
  1167: 'ER_WRONG_KEY_COLUMN',
  1168: 'ER_WRONG_MRG_TABLE',
  1169: 'ER_DUP_UNIQUE',
  1170: 'ER_BLOB_KEY_WITHOUT_LENGTH',
  1171: 'ER_PRIMARY_CANT_HAVE_NULL',
  1172: 'ER_TOO_MANY_ROWS',
  1173: 'ER_REQUIRES_PRIMARY_KEY',
  1174: 'ER_NO_RAID_COMPILED',
  1175: 'ER_UPDATE_WITHOUT_KEY_IN_SAFE_MODE',
  1176: 'ER_KEY_DOES_NOT_EXITS',
  1177: 'ER_CHECK_NO_SUCH_TABLE',
  1178: 'ER_CHECK_NOT_IMPLEMENTED',
  1179: 'ER_CANT_DO_THIS_DURING_AN_TRANSACTION',
  1180: 'ER_ERROR_DURING_COMMIT',
  1181: 'ER_ERROR_DURING_ROLLBACK',
  1182: 'ER_ERROR_DURING_FLUSH_LOGS',
  1183: 'ER_ERROR_DURING_CHECKPOINT',
  1184: 'ER_NEW_ABORTING_CONNECTION',
  1185: 'ER_DUMP_NOT_IMPLEMENTED',
  1186: 'ER_FLUSH_SOURCE_BINLOG_CLOSED',
  1187: 'ER_INDEX_REBUILD',
  1188: 'ER_SOURCE',
  1189: 'ER_SOURCE_NET_READ',
  1190: 'ER_SOURCE_NET_WRITE',
  1191: 'ER_FT_MATCHING_KEY_NOT_FOUND',
  1192: 'ER_LOCK_OR_ACTIVE_TRANSACTION',
  1193: 'ER_UNKNOWN_SYSTEM_VARIABLE',
  1194: 'ER_CRASHED_ON_USAGE',
  1195: 'ER_CRASHED_ON_REPAIR',
  1196: 'ER_WARNING_NOT_COMPLETE_ROLLBACK',
  1197: 'ER_TRANS_CACHE_FULL',
  1198: 'ER_REPLICA_MUST_STOP',
  1199: 'ER_REPLICA_NOT_RUNNING',
  1200: 'ER_BAD_REPLICA',
  1201: 'ER_SOURCE_INFO',
  1202: 'ER_REPLICA_THREAD',
  1203: 'ER_TOO_MANY_USER_CONNECTIONS',
  1204: 'ER_SET_CONSTANTS_ONLY',
  1205: 'ER_LOCK_WAIT_TIMEOUT',
  1206: 'ER_LOCK_TABLE_FULL',
  1207: 'ER_READ_ONLY_TRANSACTION',
  1208: 'ER_DROP_DB_WITH_READ_LOCK',
  1209: 'ER_CREATE_DB_WITH_READ_LOCK',
  1210: 'ER_WRONG_ARGUMENTS',
  1211: 'ER_NO_PERMISSION_TO_CREATE_USER',
  1212: 'ER_UNION_TABLES_IN_DIFFERENT_DIR',
  1213: 'ER_LOCK_DEADLOCK',
  1214: 'ER_TABLE_CANT_HANDLE_FT',
  1215: 'ER_CANNOT_ADD_FOREIGN',
  1216: 'ER_NO_REFERENCED_ROW',
  1217: 'ER_ROW_IS_REFERENCED',
  1218: 'ER_CONNECT_TO_SOURCE',
  1219: 'ER_QUERY_ON_SOURCE',
  1220: 'ER_ERROR_WHEN_EXECUTING_COMMAND',
  1221: 'ER_WRONG_USAGE',
  1222: 'ER_WRONG_NUMBER_OF_COLUMNS_IN_SELECT',
  1223: 'ER_CANT_UPDATE_WITH_READLOCK',
  1224: 'ER_MIXING_NOT_ALLOWED',
  1225: 'ER_DUP_ARGUMENT',
  1226: 'ER_USER_LIMIT_REACHED',
  1227: 'ER_SPECIFIC_ACCESS_DENIED_ERROR',
  1228: 'ER_LOCAL_VARIABLE',
  1229: 'ER_GLOBAL_VARIABLE',
  1230: 'ER_NO_DEFAULT',
  1231: 'ER_WRONG_VALUE_FOR_VAR',
  1232: 'ER_WRONG_TYPE_FOR_VAR',
  1233: 'ER_VAR_CANT_BE_READ',
  1234: 'ER_CANT_USE_OPTION_HERE',
  1235: 'ER_NOT_SUPPORTED_YET',
  1236: 'ER_SOURCE_FATAL_ERROR_READING_BINLOG',
  1237: 'ER_REPLICA_IGNORED_TABLE',
  1238: 'ER_INCORRECT_GLOBAL_LOCAL_VAR',
  1239: 'ER_WRONG_FK_DEF',
  1240: 'ER_KEY_REF_DO_NOT_MATCH_TABLE_REF',
  1241: 'ER_OPERAND_COLUMNS',
  1242: 'ER_SUBQUERY_NO_1_ROW',
  1243: 'ER_UNKNOWN_STMT_HANDLER',
  1244: 'ER_CORRUPT_HELP_DB',
  1245: 'ER_CYCLIC_REFERENCE',
  1246: 'ER_AUTO_CONVERT',
  1247: 'ER_ILLEGAL_REFERENCE',
  1248: 'ER_DERIVED_MUST_HAVE_ALIAS',
  1249: 'ER_SELECT_REDUCED',
  1250: 'ER_TABLENAME_NOT_ALLOWED_HERE',
  1251: 'ER_NOT_SUPPORTED_AUTH_MODE',
  1252: 'ER_SPATIAL_CANT_HAVE_NULL',
  1253: 'ER_COLLATION_CHARSET_MISMATCH',
  1254: 'ER_REPLICA_WAS_RUNNING',
  1255: 'ER_REPLICA_WAS_NOT_RUNNING',
  1256: 'ER_TOO_BIG_FOR_UNCOMPRESS',
  1257: 'ER_ZLIB_Z_MEM_ERROR',
  1258: 'ER_ZLIB_Z_BUF_ERROR',
  1259: 'ER_ZLIB_Z_DATA_ERROR',
  1260: 'ER_CUT_VALUE_GROUP_CONCAT',
  1261: 'ER_WARN_TOO_FEW_RECORDS',
  1262: 'ER_WARN_TOO_MANY_RECORDS',
  1263: 'ER_WARN_NULL_TO_NOTNULL',
  1264: 'ER_WARN_DATA_OUT_OF_RANGE',
  1265: 'ER_WARN_DATA_TRUNCATED',
  1266: 'ER_WARN_USING_OTHER_HANDLER',
  1267: 'ER_CANT_AGGREGATE_2COLLATIONS',
  1268: 'ER_DROP_USER',
  1269: 'ER_REVOKE_GRANTS',
  1270: 'ER_CANT_AGGREGATE_3COLLATIONS',
  1271: 'ER_CANT_AGGREGATE_NCOLLATIONS',
  1272: 'ER_VARIABLE_IS_NOT_STRUCT',
  1273: 'ER_UNKNOWN_COLLATION',
  1274: 'ER_REPLICA_IGNORED_SSL_PARAMS',
  1275: 'ER_SERVER_IS_IN_SECURE_AUTH_MODE',
  1276: 'ER_WARN_FIELD_RESOLVED',
  1277: 'ER_BAD_REPLICA_UNTIL_COND',
  1278: 'ER_MISSING_SKIP_REPLICA',
  1279: 'ER_UNTIL_COND_IGNORED',
  1280: 'ER_WRONG_NAME_FOR_INDEX',
  1281: 'ER_WRONG_NAME_FOR_CATALOG',
  1282: 'ER_WARN_QC_RESIZE',
  1283: 'ER_BAD_FT_COLUMN',
  1284: 'ER_UNKNOWN_KEY_CACHE',
  1285: 'ER_WARN_HOSTNAME_WONT_WORK',
  1286: 'ER_UNKNOWN_STORAGE_ENGINE',
  1287: 'ER_WARN_DEPRECATED_SYNTAX',
  1288: 'ER_NON_UPDATABLE_TABLE',
  1289: 'ER_FEATURE_DISABLED',
  1290: 'ER_OPTION_PREVENTS_STATEMENT',
  1291: 'ER_DUPLICATED_VALUE_IN_TYPE',
  1292: 'ER_TRUNCATED_WRONG_VALUE',
  1293: 'ER_TOO_MUCH_AUTO_TIMESTAMP_COLS',
  1294: 'ER_INVALID_ON_UPDATE',
  1295: 'ER_UNSUPPORTED_PS',
  1296: 'ER_GET_ERRMSG',
  1297: 'ER_GET_TEMPORARY_ERRMSG',
  1298: 'ER_UNKNOWN_TIME_ZONE',
  1299: 'ER_WARN_INVALID_TIMESTAMP',
  1300: 'ER_INVALID_CHARACTER_STRING',
  1301: 'ER_WARN_ALLOWED_PACKET_OVERFLOWED',
  1302: 'ER_CONFLICTING_DECLARATIONS',
  1303: 'ER_SP_NO_RECURSIVE_CREATE',
  1304: 'ER_SP_ALREADY_EXISTS',
  1305: 'ER_SP_DOES_NOT_EXIST',
  1306: 'ER_SP_DROP_FAILED',
  1307: 'ER_SP_STORE_FAILED',
  1308: 'ER_SP_LILABEL_MISMATCH',
  1309: 'ER_SP_LABEL_REDEFINE',
  1310: 'ER_SP_LABEL_MISMATCH',
  1311: 'ER_SP_UNINIT_VAR',
  1312: 'ER_SP_BADSELECT',
  1313: 'ER_SP_BADRETURN',
  1314: 'ER_SP_BADSTATEMENT',
  1315: 'ER_UPDATE_LOG_DEPRECATED_IGNORED',
  1316: 'ER_UPDATE_LOG_DEPRECATED_TRANSLATED',
  1317: 'ER_QUERY_INTERRUPTED',
  1318: 'ER_SP_WRONG_NO_OF_ARGS',
  1319: 'ER_SP_COND_MISMATCH',
  1320: 'ER_SP_NORETURN',
  1321: 'ER_SP_NORETURNEND',
  1322: 'ER_SP_BAD_CURSOR_QUERY',
  1323: 'ER_SP_BAD_CURSOR_SELECT',
  1324: 'ER_SP_CURSOR_MISMATCH',
  1325: 'ER_SP_CURSOR_ALREADY_OPEN',
  1326: 'ER_SP_CURSOR_NOT_OPEN',
  1327: 'ER_SP_UNDECLARED_VAR',
  1328: 'ER_SP_WRONG_NO_OF_FETCH_ARGS',
  1329: 'ER_SP_FETCH_NO_DATA',
  1330: 'ER_SP_DUP_PARAM',
  1331: 'ER_SP_DUP_VAR',
  1332: 'ER_SP_DUP_COND',
  1333: 'ER_SP_DUP_CURS',
  1334: 'ER_SP_CANT_ALTER',
  1335: 'ER_SP_SUBSELECT_NYI',
  1336: 'ER_STMT_NOT_ALLOWED_IN_SF_OR_TRG',
  1337: 'ER_SP_VARCOND_AFTER_CURSHNDLR',
  1338: 'ER_SP_CURSOR_AFTER_HANDLER',
  1339: 'ER_SP_CASE_NOT_FOUND',
  1340: 'ER_FPARSER_TOO_BIG_FILE',
  1341: 'ER_FPARSER_BAD_HEADER',
  1342: 'ER_FPARSER_EOF_IN_COMMENT',
  1343: 'ER_FPARSER_ERROR_IN_PARAMETER',
  1344: 'ER_FPARSER_EOF_IN_UNKNOWN_PARAMETER',
  1345: 'ER_VIEW_NO_EXPLAIN',
  1346: 'ER_FRM_UNKNOWN_TYPE',
  1347: 'ER_WRONG_OBJECT',
  1348: 'ER_NONUPDATEABLE_COLUMN',
  1349: 'ER_VIEW_SELECT_DERIVED',
  1350: 'ER_VIEW_SELECT_CLAUSE',
  1351: 'ER_VIEW_SELECT_VARIABLE',
  1352: 'ER_VIEW_SELECT_TMPTABLE',
  1353: 'ER_VIEW_WRONG_LIST',
  1354: 'ER_WARN_VIEW_MERGE',
  1355: 'ER_WARN_VIEW_WITHOUT_KEY',
  1356: 'ER_VIEW_INVALID',
  1357: 'ER_SP_NO_DROP_SP',
  1358: 'ER_SP_GOTO_IN_HNDLR',
  1359: 'ER_TRG_ALREADY_EXISTS',
  1360: 'ER_TRG_DOES_NOT_EXIST',
  1361: 'ER_TRG_ON_VIEW_OR_TEMP_TABLE',
  1362: 'ER_TRG_CANT_CHANGE_ROW',
  1363: 'ER_TRG_NO_SUCH_ROW_IN_TRG',
  1364: 'ER_NO_DEFAULT_FOR_FIELD',
  1365: 'ER_DIVISION_BY_ZERO',
  1366: 'ER_TRUNCATED_WRONG_VALUE_FOR_FIELD',
  1367: 'ER_ILLEGAL_VALUE_FOR_TYPE',
  1368: 'ER_VIEW_NONUPD_CHECK',
  1369: 'ER_VIEW_CHECK_FAILED',
  1370: 'ER_PROCACCESS_DENIED_ERROR',
  1371: 'ER_RELAY_LOG_FAIL',
  1372: 'ER_PASSWD_LENGTH',
  1373: 'ER_UNKNOWN_TARGET_BINLOG',
  1374: 'ER_IO_ERR_LOG_INDEX_READ',
  1375: 'ER_BINLOG_PURGE_PROHIBITED',
  1376: 'ER_FSEEK_FAIL',
  1377: 'ER_BINLOG_PURGE_FATAL_ERR',
  1378: 'ER_LOG_IN_USE',
  1379: 'ER_LOG_PURGE_UNKNOWN_ERR',
  1380: 'ER_RELAY_LOG_INIT',
  1381: 'ER_NO_BINARY_LOGGING',
  1382: 'ER_RESERVED_SYNTAX',
  1383: 'ER_WSAS_FAILED',
  1384: 'ER_DIFF_GROUPS_PROC',
  1385: 'ER_NO_GROUP_FOR_PROC',
  1386: 'ER_ORDER_WITH_PROC',
  1387: 'ER_LOGGING_PROHIBIT_CHANGING_OF',
  1388: 'ER_NO_FILE_MAPPING',
  1389: 'ER_WRONG_MAGIC',
  1390: 'ER_PS_MANY_PARAM',
  1391: 'ER_KEY_PART_0',
  1392: 'ER_VIEW_CHECKSUM',
  1393: 'ER_VIEW_MULTIUPDATE',
  1394: 'ER_VIEW_NO_INSERT_FIELD_LIST',
  1395: 'ER_VIEW_DELETE_MERGE_VIEW',
  1396: 'ER_CANNOT_USER',
  1397: 'ER_XAER_NOTA',
  1398: 'ER_XAER_INVAL',
  1399: 'ER_XAER_RMFAIL',
  1400: 'ER_XAER_OUTSIDE',
  1401: 'ER_XA_RMERR',
  1402: 'ER_XA_RBROLLBACK',
  1403: 'ER_NONEXISTING_PROC_GRANT',
  1404: 'ER_PROC_AUTO_GRANT_FAIL',
  1405: 'ER_PROC_AUTO_REVOKE_FAIL',
  1406: 'ER_DATA_TOO_LONG',
  1407: 'ER_SP_BAD_SQLSTATE',
  1408: 'ER_STARTUP',
  1409: 'ER_LOAD_FROM_FIXED_SIZE_ROWS_TO_VAR',
  1410: 'ER_CANT_CREATE_USER_WITH_GRANT',
  1411: 'ER_WRONG_VALUE_FOR_TYPE',
  1412: 'ER_TABLE_DEF_CHANGED',
  1413: 'ER_SP_DUP_HANDLER',
  1414: 'ER_SP_NOT_VAR_ARG',
  1415: 'ER_SP_NO_RETSET',
  1416: 'ER_CANT_CREATE_GEOMETRY_OBJECT',
  1417: 'ER_FAILED_ROUTINE_BREAK_BINLOG',
  1418: 'ER_BINLOG_UNSAFE_ROUTINE',
  1419: 'ER_BINLOG_CREATE_ROUTINE_NEED_SUPER',
  1420: 'ER_EXEC_STMT_WITH_OPEN_CURSOR',
  1421: 'ER_STMT_HAS_NO_OPEN_CURSOR',
  1422: 'ER_COMMIT_NOT_ALLOWED_IN_SF_OR_TRG',
  1423: 'ER_NO_DEFAULT_FOR_VIEW_FIELD',
  1424: 'ER_SP_NO_RECURSION',
  1425: 'ER_TOO_BIG_SCALE',
  1426: 'ER_TOO_BIG_PRECISION',
  1427: 'ER_M_BIGGER_THAN_D',
  1428: 'ER_WRONG_LOCK_OF_SYSTEM_TABLE',
  1429: 'ER_CONNECT_TO_FOREIGN_DATA_SOURCE',
  1430: 'ER_QUERY_ON_FOREIGN_DATA_SOURCE',
  1431: 'ER_FOREIGN_DATA_SOURCE_DOESNT_EXIST',
  1432: 'ER_FOREIGN_DATA_STRING_INVALID_CANT_CREATE',
  1433: 'ER_FOREIGN_DATA_STRING_INVALID',
  1434: 'ER_CANT_CREATE_FEDERATED_TABLE',
  1435: 'ER_TRG_IN_WRONG_SCHEMA',
  1436: 'ER_STACK_OVERRUN_NEED_MORE',
  1437: 'ER_TOO_LONG_BODY',
  1438: 'ER_WARN_CANT_DROP_DEFAULT_KEYCACHE',
  1439: 'ER_TOO_BIG_DISPLAYWIDTH',
  1440: 'ER_XAER_DUPID',
  1441: 'ER_DATETIME_FUNCTION_OVERFLOW',
  1442: 'ER_CANT_UPDATE_USED_TABLE_IN_SF_OR_TRG',
  1443: 'ER_VIEW_PREVENT_UPDATE',
  1444: 'ER_PS_NO_RECURSION',
  1445: 'ER_SP_CANT_SET_AUTOCOMMIT',
  1446: 'ER_MALFORMED_DEFINER',
  1447: 'ER_VIEW_FRM_NO_USER',
  1448: 'ER_VIEW_OTHER_USER',
  1449: 'ER_NO_SUCH_USER',
  1450: 'ER_FORBID_SCHEMA_CHANGE',
  1451: 'ER_ROW_IS_REFERENCED_2',
  1452: 'ER_NO_REFERENCED_ROW_2',
  1453: 'ER_SP_BAD_VAR_SHADOW',
  1454: 'ER_TRG_NO_DEFINER',
  1455: 'ER_OLD_FILE_FORMAT',
  1456: 'ER_SP_RECURSION_LIMIT',
  1457: 'ER_SP_PROC_TABLE_CORRUPT',
  1458: 'ER_SP_WRONG_NAME',
  1459: 'ER_TABLE_NEEDS_UPGRADE',
  1460: 'ER_SP_NO_AGGREGATE',
  1461: 'ER_MAX_PREPARED_STMT_COUNT_REACHED',
  1462: 'ER_VIEW_RECURSIVE',
  1463: 'ER_NON_GROUPING_FIELD_USED',
  1464: 'ER_TABLE_CANT_HANDLE_SPKEYS',
  1465: 'ER_NO_TRIGGERS_ON_SYSTEM_SCHEMA',
  1466: 'ER_REMOVED_SPACES',
  1467: 'ER_AUTOINC_READ_FAILED',
  1468: 'ER_USERNAME',
  1469: 'ER_HOSTNAME',
  1470: 'ER_WRONG_STRING_LENGTH',
  1471: 'ER_NON_INSERTABLE_TABLE',
  1472: 'ER_ADMIN_WRONG_MRG_TABLE',
  1473: 'ER_TOO_HIGH_LEVEL_OF_NESTING_FOR_SELECT',
  1474: 'ER_NAME_BECOMES_EMPTY',
  1475: 'ER_AMBIGUOUS_FIELD_TERM',
  1476: 'ER_FOREIGN_SERVER_EXISTS',
  1477: 'ER_FOREIGN_SERVER_DOESNT_EXIST',
  1478: 'ER_ILLEGAL_HA_CREATE_OPTION',
  1479: 'ER_PARTITION_REQUIRES_VALUES_ERROR',
  1480: 'ER_PARTITION_WRONG_VALUES_ERROR',
  1481: 'ER_PARTITION_MAXVALUE_ERROR',
  1482: 'ER_PARTITION_SUBPARTITION_ERROR',
  1483: 'ER_PARTITION_SUBPART_MIX_ERROR',
  1484: 'ER_PARTITION_WRONG_NO_PART_ERROR',
  1485: 'ER_PARTITION_WRONG_NO_SUBPART_ERROR',
  1486: 'ER_WRONG_EXPR_IN_PARTITION_FUNC_ERROR',
  1487: 'ER_NO_CONST_EXPR_IN_RANGE_OR_LIST_ERROR',
  1488: 'ER_FIELD_NOT_FOUND_PART_ERROR',
  1489: 'ER_LIST_OF_FIELDS_ONLY_IN_HASH_ERROR',
  1490: 'ER_INCONSISTENT_PARTITION_INFO_ERROR',
  1491: 'ER_PARTITION_FUNC_NOT_ALLOWED_ERROR',
  1492: 'ER_PARTITIONS_MUST_BE_DEFINED_ERROR',
  1493: 'ER_RANGE_NOT_INCREASING_ERROR',
  1494: 'ER_INCONSISTENT_TYPE_OF_FUNCTIONS_ERROR',
  1495: 'ER_MULTIPLE_DEF_CONST_IN_LIST_PART_ERROR',
  1496: 'ER_PARTITION_ENTRY_ERROR',
  1497: 'ER_MIX_HANDLER_ERROR',
  1498: 'ER_PARTITION_NOT_DEFINED_ERROR',
  1499: 'ER_TOO_MANY_PARTITIONS_ERROR',
  1500: 'ER_SUBPARTITION_ERROR',
  1501: 'ER_CANT_CREATE_HANDLER_FILE',
  1502: 'ER_BLOB_FIELD_IN_PART_FUNC_ERROR',
  1503: 'ER_UNIQUE_KEY_NEED_ALL_FIELDS_IN_PF',
  1504: 'ER_NO_PARTS_ERROR',
  1505: 'ER_PARTITION_MGMT_ON_NONPARTITIONED',
  1506: 'ER_FOREIGN_KEY_ON_PARTITIONED',
  1507: 'ER_DROP_PARTITION_NON_EXISTENT',
  1508: 'ER_DROP_LAST_PARTITION',
  1509: 'ER_COALESCE_ONLY_ON_HASH_PARTITION',
  1510: 'ER_REORG_HASH_ONLY_ON_SAME_NO',
  1511: 'ER_REORG_NO_PARAM_ERROR',
  1512: 'ER_ONLY_ON_RANGE_LIST_PARTITION',
  1513: 'ER_ADD_PARTITION_SUBPART_ERROR',
  1514: 'ER_ADD_PARTITION_NO_NEW_PARTITION',
  1515: 'ER_COALESCE_PARTITION_NO_PARTITION',
  1516: 'ER_REORG_PARTITION_NOT_EXIST',
  1517: 'ER_SAME_NAME_PARTITION',
  1518: 'ER_NO_BINLOG_ERROR',
  1519: 'ER_CONSECUTIVE_REORG_PARTITIONS',
  1520: 'ER_REORG_OUTSIDE_RANGE',
  1521: 'ER_PARTITION_FUNCTION_FAILURE',
  1522: 'ER_PART_STATE_ERROR',
  1523: 'ER_LIMITED_PART_RANGE',
  1524: 'ER_PLUGIN_IS_NOT_LOADED',
  1525: 'ER_WRONG_VALUE',
  1526: 'ER_NO_PARTITION_FOR_GIVEN_VALUE',
  1527: 'ER_FILEGROUP_OPTION_ONLY_ONCE',
  1528: 'ER_CREATE_FILEGROUP_FAILED',
  1529: 'ER_DROP_FILEGROUP_FAILED',
  1530: 'ER_TABLESPACE_AUTO_EXTEND_ERROR',
  1531: 'ER_WRONG_SIZE_NUMBER',
  1532: 'ER_SIZE_OVERFLOW_ERROR',
  1533: 'ER_ALTER_FILEGROUP_FAILED',
  1534: 'ER_BINLOG_ROW_LOGGING_FAILED',
  1535: 'ER_BINLOG_ROW_WRONG_TABLE_DEF',
  1536: 'ER_BINLOG_ROW_RBR_TO_SBR',
  1537: 'ER_EVENT_ALREADY_EXISTS',
  1538: 'ER_EVENT_STORE_FAILED',
  1539: 'ER_EVENT_DOES_NOT_EXIST',
  1540: 'ER_EVENT_CANT_ALTER',
  1541: 'ER_EVENT_DROP_FAILED',
  1542: 'ER_EVENT_INTERVAL_NOT_POSITIVE_OR_TOO_BIG',
  1543: 'ER_EVENT_ENDS_BEFORE_STARTS',
  1544: 'ER_EVENT_EXEC_TIME_IN_THE_PAST',
  1545: 'ER_EVENT_OPEN_TABLE_FAILED',
  1546: 'ER_EVENT_NEITHER_M_EXPR_NOR_M_AT',
  1547: 'ER_COL_COUNT_DOESNT_MATCH_CORRUPTED',
  1548: 'ER_CANNOT_LOAD_FROM_TABLE',
  1549: 'ER_EVENT_CANNOT_DELETE',
  1550: 'ER_EVENT_COMPILE_ERROR',
  1551: 'ER_EVENT_SAME_NAME',
  1552: 'ER_EVENT_DATA_TOO_LONG',
  1553: 'ER_DROP_INDEX_FK',
  1554: 'ER_WARN_DEPRECATED_SYNTAX_WITH_VER',
  1555: 'ER_CANT_WRITE_LOCK_LOG_TABLE',
  1556: 'ER_CANT_LOCK_LOG_TABLE',
  1557: 'ER_FOREIGN_DUPLICATE_KEY',
  1558: 'ER_COL_COUNT_DOESNT_MATCH_PLEASE_UPDATE',
  1559: 'ER_TEMP_TABLE_PREVENTS_SWITCH_OUT_OF_RBR',
  1560: 'ER_STORED_FUNCTION_PREVENTS_SWITCH_BINLOG_FORMAT',
  1561: 'ER_NDB_CANT_SWITCH_BINLOG_FORMAT',
  1562: 'ER_PARTITION_NO_TEMPORARY',
  1563: 'ER_PARTITION_CONST_DOMAIN_ERROR',
  1564: 'ER_PARTITION_FUNCTION_IS_NOT_ALLOWED',
  1565: 'ER_DDL_LOG_ERROR',
  1566: 'ER_NULL_IN_VALUES_LESS_THAN',
  1567: 'ER_WRONG_PARTITION_NAME',
  1568: 'ER_CANT_CHANGE_TX_ISOLATION',
  1569: 'ER_DUP_ENTRY_AUTOINCREMENT_CASE',
  1570: 'ER_EVENT_MODIFY_QUEUE_ERROR',
  1571: 'ER_EVENT_SET_VAR_ERROR',
  1572: 'ER_PARTITION_MERGE_ERROR',
  1573: 'ER_CANT_ACTIVATE_LOG',
  1574: 'ER_RBR_NOT_AVAILABLE',
  1575: 'ER_BASE64_DECODE_ERROR',
  1576: 'ER_EVENT_RECURSION_FORBIDDEN',
  1577: 'ER_EVENTS_DB_ERROR',
  1578: 'ER_ONLY_INTEGERS_ALLOWED',
  1579: 'ER_UNSUPORTED_LOG_ENGINE',
  1580: 'ER_BAD_LOG_STATEMENT',
  1581: 'ER_CANT_RENAME_LOG_TABLE',
  1582: 'ER_WRONG_PARAMCOUNT_TO_NATIVE_FCT',
  1583: 'ER_WRONG_PARAMETERS_TO_NATIVE_FCT',
  1584: 'ER_WRONG_PARAMETERS_TO_STORED_FCT',
  1585: 'ER_NATIVE_FCT_NAME_COLLISION',
  1586: 'ER_DUP_ENTRY_WITH_KEY_NAME',
  1587: 'ER_BINLOG_PURGE_EMFILE',
  1588: 'ER_EVENT_CANNOT_CREATE_IN_THE_PAST',
  1589: 'ER_EVENT_CANNOT_ALTER_IN_THE_PAST',
  1590: 'ER_REPLICA_INCIDENT',
  1591: 'ER_NO_PARTITION_FOR_GIVEN_VALUE_SILENT',
  1592: 'ER_BINLOG_UNSAFE_STATEMENT',
  1593: 'ER_REPLICA_FATAL_ERROR',
  1594: 'ER_REPLICA_RELAY_LOG_READ_FAILURE',
  1595: 'ER_REPLICA_RELAY_LOG_WRITE_FAILURE',
  1596: 'ER_REPLICA_CREATE_EVENT_FAILURE',
  1597: 'ER_REPLICA_SOURCE_COM_FAILURE',
  1598: 'ER_BINLOG_LOGGING_IMPOSSIBLE',
  1599: 'ER_VIEW_NO_CREATION_CTX',
  1600: 'ER_VIEW_INVALID_CREATION_CTX',
  1601: 'ER_SR_INVALID_CREATION_CTX',
  1602: 'ER_TRG_CORRUPTED_FILE',
  1603: 'ER_TRG_NO_CREATION_CTX',
  1604: 'ER_TRG_INVALID_CREATION_CTX',
  1605: 'ER_EVENT_INVALID_CREATION_CTX',
  1606: 'ER_TRG_CANT_OPEN_TABLE',
  1607: 'ER_CANT_CREATE_SROUTINE',
  1608: 'ER_NEVER_USED',
  1609: 'ER_NO_FORMAT_DESCRIPTION_EVENT_BEFORE_BINLOG_STATEMENT',
  1610: 'ER_REPLICA_CORRUPT_EVENT',
  1611: 'ER_LOAD_DATA_INVALID_COLUMN',
  1612: 'ER_LOG_PURGE_NO_FILE',
  1613: 'ER_XA_RBTIMEOUT',
  1614: 'ER_XA_RBDEADLOCK',
  1615: 'ER_NEED_REPREPARE',
  1616: 'ER_DELAYED_NOT_SUPPORTED',
  1617: 'WARN_NO_SOURCE_INFO',
  1618: 'WARN_OPTION_IGNORED',
  1619: 'WARN_PLUGIN_DELETE_BUILTIN',
  1620: 'WARN_PLUGIN_BUSY',
  1621: 'ER_VARIABLE_IS_READONLY',
  1622: 'ER_WARN_ENGINE_TRANSACTION_ROLLBACK',
  1623: 'ER_REPLICA_HEARTBEAT_FAILURE',
  1624: 'ER_REPLICA_HEARTBEAT_VALUE_OUT_OF_RANGE',
  1625: 'ER_NDB_REPLICATION_SCHEMA_ERROR',
  1626: 'ER_CONFLICT_FN_PARSE_ERROR',
  1627: 'ER_EXCEPTIONS_WRITE_ERROR',
  1628: 'ER_TOO_LONG_TABLE_COMMENT',
  1629: 'ER_TOO_LONG_FIELD_COMMENT',
  1630: 'ER_FUNC_INEXISTENT_NAME_COLLISION',
  1631: 'ER_DATABASE_NAME',
  1632: 'ER_TABLE_NAME',
  1633: 'ER_PARTITION_NAME',
  1634: 'ER_SUBPARTITION_NAME',
  1635: 'ER_TEMPORARY_NAME',
  1636: 'ER_RENAMED_NAME',
  1637: 'ER_TOO_MANY_CONCURRENT_TRXS',
  1638: 'WARN_NON_ASCII_SEPARATOR_NOT_IMPLEMENTED',
  1639: 'ER_DEBUG_SYNC_TIMEOUT',
  1640: 'ER_DEBUG_SYNC_HIT_LIMIT',
  1641: 'ER_DUP_SIGNAL_SET',
  1642: 'ER_SIGNAL_WARN',
  1643: 'ER_SIGNAL_NOT_FOUND',
  1644: 'ER_SIGNAL_EXCEPTION',
  1645: 'ER_RESIGNAL_WITHOUT_ACTIVE_HANDLER',
  1646: 'ER_SIGNAL_BAD_CONDITION_TYPE',
  1647: 'WARN_COND_ITEM_TRUNCATED',
  1648: 'ER_COND_ITEM_TOO_LONG',
  1649: 'ER_UNKNOWN_LOCALE',
  1650: 'ER_REPLICA_IGNORE_SERVER_IDS',
  1651: 'ER_QUERY_CACHE_DISABLED',
  1652: 'ER_SAME_NAME_PARTITION_FIELD',
  1653: 'ER_PARTITION_COLUMN_LIST_ERROR',
  1654: 'ER_WRONG_TYPE_COLUMN_VALUE_ERROR',
  1655: 'ER_TOO_MANY_PARTITION_FUNC_FIELDS_ERROR',
  1656: 'ER_MAXVALUE_IN_VALUES_IN',
  1657: 'ER_TOO_MANY_VALUES_ERROR',
  1658: 'ER_ROW_SINGLE_PARTITION_FIELD_ERROR',
  1659: 'ER_FIELD_TYPE_NOT_ALLOWED_AS_PARTITION_FIELD',
  1660: 'ER_PARTITION_FIELDS_TOO_LONG',
  1661: 'ER_BINLOG_ROW_ENGINE_AND_STMT_ENGINE',
  1662: 'ER_BINLOG_ROW_MODE_AND_STMT_ENGINE',
  1663: 'ER_BINLOG_UNSAFE_AND_STMT_ENGINE',
  1664: 'ER_BINLOG_ROW_INJECTION_AND_STMT_ENGINE',
  1665: 'ER_BINLOG_STMT_MODE_AND_ROW_ENGINE',
  1666: 'ER_BINLOG_ROW_INJECTION_AND_STMT_MODE',
  1667: 'ER_BINLOG_MULTIPLE_ENGINES_AND_SELF_LOGGING_ENGINE',
  1668: 'ER_BINLOG_UNSAFE_LIMIT',
  1669: 'ER_BINLOG_UNSAFE_INSERT_DELAYED',
  1670: 'ER_BINLOG_UNSAFE_SYSTEM_TABLE',
  1671: 'ER_BINLOG_UNSAFE_AUTOINC_COLUMNS',
  1672: 'ER_BINLOG_UNSAFE_UDF',
  1673: 'ER_BINLOG_UNSAFE_SYSTEM_VARIABLE',
  1674: 'ER_BINLOG_UNSAFE_SYSTEM_FUNCTION',
  1675: 'ER_BINLOG_UNSAFE_NONTRANS_AFTER_TRANS',
  1676: 'ER_MESSAGE_AND_STATEMENT',
  1677: 'ER_REPLICA_CONVERSION_FAILED',
  1678: 'ER_REPLICA_CANT_CREATE_CONVERSION',
  1679: 'ER_INSIDE_TRANSACTION_PREVENTS_SWITCH_BINLOG_FORMAT',
  1680: 'ER_PATH_LENGTH',
  1681: 'ER_WARN_DEPRECATED_SYNTAX_NO_REPLACEMENT',
  1682: 'ER_WRONG_NATIVE_TABLE_STRUCTURE',
  1683: 'ER_WRONG_PERFSCHEMA_USAGE',
  1684: 'ER_WARN_I_S_SKIPPED_TABLE',
  1685: 'ER_INSIDE_TRANSACTION_PREVENTS_SWITCH_BINLOG_DIRECT',
  1686: 'ER_STORED_FUNCTION_PREVENTS_SWITCH_BINLOG_DIRECT',
  1687: 'ER_SPATIAL_MUST_HAVE_GEOM_COL',
  1688: 'ER_TOO_LONG_INDEX_COMMENT',
  1689: 'ER_LOCK_ABORTED',
  1690: 'ER_DATA_OUT_OF_RANGE',
  1691: 'ER_WRONG_SPVAR_TYPE_IN_LIMIT',
  1692: 'ER_BINLOG_UNSAFE_MULTIPLE_ENGINES_AND_SELF_LOGGING_ENGINE',
  1693: 'ER_BINLOG_UNSAFE_MIXED_STATEMENT',
  1694: 'ER_INSIDE_TRANSACTION_PREVENTS_SWITCH_SQL_LOG_BIN',
  1695: 'ER_STORED_FUNCTION_PREVENTS_SWITCH_SQL_LOG_BIN',
  1696: 'ER_FAILED_READ_FROM_PAR_FILE',
  1697: 'ER_VALUES_IS_NOT_INT_TYPE_ERROR',
  1698: 'ER_ACCESS_DENIED_NO_PASSWORD_ERROR',
  1699: 'ER_SET_PASSWORD_AUTH_PLUGIN',
  1700: 'ER_GRANT_PLUGIN_USER_EXISTS',
  1701: 'ER_TRUNCATE_ILLEGAL_FK',
  1702: 'ER_PLUGIN_IS_PERMANENT',
  1703: 'ER_REPLICA_HEARTBEAT_VALUE_OUT_OF_RANGE_MIN',
  1704: 'ER_REPLICA_HEARTBEAT_VALUE_OUT_OF_RANGE_MAX',
  1705: 'ER_STMT_CACHE_FULL',
  1706: 'ER_MULTI_UPDATE_KEY_CONFLICT',
  1707: 'ER_TABLE_NEEDS_REBUILD',
  1708: 'WARN_OPTION_BELOW_LIMIT',
  1709: 'ER_INDEX_COLUMN_TOO_LONG',
  1710: 'ER_ERROR_IN_TRIGGER_BODY',
  1711: 'ER_ERROR_IN_UNKNOWN_TRIGGER_BODY',
  1712: 'ER_INDEX_CORRUPT',
  1713: 'ER_UNDO_RECORD_TOO_BIG',
  1714: 'ER_BINLOG_UNSAFE_INSERT_IGNORE_SELECT',
  1715: 'ER_BINLOG_UNSAFE_INSERT_SELECT_UPDATE',
  1716: 'ER_BINLOG_UNSAFE_REPLACE_SELECT',
  1717: 'ER_BINLOG_UNSAFE_CREATE_IGNORE_SELECT',
  1718: 'ER_BINLOG_UNSAFE_CREATE_REPLACE_SELECT',
  1719: 'ER_BINLOG_UNSAFE_UPDATE_IGNORE',
  1720: 'ER_PLUGIN_NO_UNINSTALL',
  1721: 'ER_PLUGIN_NO_INSTALL',
  1722: 'ER_BINLOG_UNSAFE_WRITE_AUTOINC_SELECT',
  1723: 'ER_BINLOG_UNSAFE_CREATE_SELECT_AUTOINC',
  1724: 'ER_BINLOG_UNSAFE_INSERT_TWO_KEYS',
  1725: 'ER_TABLE_IN_FK_CHECK',
  1726: 'ER_UNSUPPORTED_ENGINE',
  1727: 'ER_BINLOG_UNSAFE_AUTOINC_NOT_FIRST',
  1728: 'ER_CANNOT_LOAD_FROM_TABLE_V2',
  1729: 'ER_SOURCE_DELAY_VALUE_OUT_OF_RANGE',
  1730: 'ER_ONLY_FD_AND_RBR_EVENTS_ALLOWED_IN_BINLOG_STATEMENT',
  1731: 'ER_PARTITION_EXCHANGE_DIFFERENT_OPTION',
  1732: 'ER_PARTITION_EXCHANGE_PART_TABLE',
  1733: 'ER_PARTITION_EXCHANGE_TEMP_TABLE',
  1734: 'ER_PARTITION_INSTEAD_OF_SUBPARTITION',
  1735: 'ER_UNKNOWN_PARTITION',
  1736: 'ER_TABLES_DIFFERENT_METADATA',
  1737: 'ER_ROW_DOES_NOT_MATCH_PARTITION',
  1738: 'ER_BINLOG_CACHE_SIZE_GREATER_THAN_MAX',
  1739: 'ER_WARN_INDEX_NOT_APPLICABLE',
  1740: 'ER_PARTITION_EXCHANGE_FOREIGN_KEY',
  1741: 'ER_NO_SUCH_KEY_VALUE',
  1742: 'ER_RPL_INFO_DATA_TOO_LONG',
  1743: 'ER_NETWORK_READ_EVENT_CHECKSUM_FAILURE',
  1744: 'ER_BINLOG_READ_EVENT_CHECKSUM_FAILURE',
  1745: 'ER_BINLOG_STMT_CACHE_SIZE_GREATER_THAN_MAX',
  1746: 'ER_CANT_UPDATE_TABLE_IN_CREATE_TABLE_SELECT',
  1747: 'ER_PARTITION_CLAUSE_ON_NONPARTITIONED',
  1748: 'ER_ROW_DOES_NOT_MATCH_GIVEN_PARTITION_SET',
  1749: 'ER_NO_SUCH_PARTITION',
  1750: 'ER_CHANGE_RPL_INFO_REPOSITORY_FAILURE',
  1751: 'ER_WARNING_NOT_COMPLETE_ROLLBACK_WITH_CREATED_TEMP_TABLE',
  1752: 'ER_WARNING_NOT_COMPLETE_ROLLBACK_WITH_DROPPED_TEMP_TABLE',
  1753: 'ER_MTS_FEATURE_IS_NOT_SUPPORTED',
  1754: 'ER_MTS_UPDATED_DBS_GREATER_MAX',
  1755: 'ER_MTS_CANT_PARALLEL',
  1756: 'ER_MTS_INCONSISTENT_DATA',
  1757: 'ER_FULLTEXT_NOT_SUPPORTED_WITH_PARTITIONING',
  1758: 'ER_DA_INVALID_CONDITION_NUMBER',
  1759: 'ER_INSECURE_PLAIN_TEXT',
  1760: 'ER_INSECURE_CHANGE_SOURCE',
  1761: 'ER_FOREIGN_DUPLICATE_KEY_WITH_CHILD_INFO',
  1762: 'ER_FOREIGN_DUPLICATE_KEY_WITHOUT_CHILD_INFO',
  1763: 'ER_SQLTHREAD_WITH_SECURE_REPLICA',
  1764: 'ER_TABLE_HAS_NO_FT',
  1765: 'ER_VARIABLE_NOT_SETTABLE_IN_SF_OR_TRIGGER',
  1766: 'ER_VARIABLE_NOT_SETTABLE_IN_TRANSACTION',
  1767: 'ER_GTID_NEXT_IS_NOT_IN_GTID_NEXT_LIST',
  1768: 'ER_CANT_CHANGE_GTID_NEXT_IN_TRANSACTION_WHEN_GTID_NEXT_LIST_IS_NULL',
  1769: 'ER_SET_STATEMENT_CANNOT_INVOKE_FUNCTION',
  1770: 'ER_GTID_NEXT_CANT_BE_AUTOMATIC_IF_GTID_NEXT_LIST_IS_NON_NULL',
  1771: 'ER_SKIPPING_LOGGED_TRANSACTION',
  1772: 'ER_MALFORMED_GTID_SET_SPECIFICATION',
  1773: 'ER_MALFORMED_GTID_SET_ENCODING',
  1774: 'ER_MALFORMED_GTID_SPECIFICATION',
  1775: 'ER_GNO_EXHAUSTED',
  1776: 'ER_BAD_REPLICA_AUTO_POSITION',
  1777: 'ER_AUTO_POSITION_REQUIRES_GTID_MODE_ON',
  1778: 'ER_CANT_DO_IMPLICIT_COMMIT_IN_TRX_WHEN_GTID_NEXT_IS_SET',
  1779: 'ER_GTID_MODE_2_OR_3_REQUIRES_ENFORCE_GTID_CONSISTENCY_ON',
  1780: 'ER_GTID_MODE_REQUIRES_BINLOG',
  1781: 'ER_CANT_SET_GTID_NEXT_TO_GTID_WHEN_GTID_MODE_IS_OFF',
  1782: 'ER_CANT_SET_GTID_NEXT_TO_ANONYMOUS_WHEN_GTID_MODE_IS_ON',
  1783: 'ER_CANT_SET_GTID_NEXT_LIST_TO_NON_NULL_WHEN_GTID_MODE_IS_OFF',
  1784: 'ER_FOUND_GTID_EVENT_WHEN_GTID_MODE_IS_OFF',
  1785: 'ER_GTID_UNSAFE_NON_TRANSACTIONAL_TABLE',
  1786: 'ER_GTID_UNSAFE_CREATE_SELECT',
  1787: 'ER_GTID_UNSAFE_CREATE_DROP_TEMPORARY_TABLE_IN_TRANSACTION',
  1788: 'ER_GTID_MODE_CAN_ONLY_CHANGE_ONE_STEP_AT_A_TIME',
  1789: 'ER_SOURCE_HAS_PURGED_REQUIRED_GTIDS',
  1790: 'ER_CANT_SET_GTID_NEXT_WHEN_OWNING_GTID',
  1791: 'ER_UNKNOWN_EXPLAIN_FORMAT',
  1792: 'ER_CANT_EXECUTE_IN_READ_ONLY_TRANSACTION',
  1793: 'ER_TOO_LONG_TABLE_PARTITION_COMMENT',
  1794: 'ER_REPLICA_CONFIGURATION',
  1795: 'ER_INNODB_FT_LIMIT',
  1796: 'ER_INNODB_NO_FT_TEMP_TABLE',
  1797: 'ER_INNODB_FT_WRONG_DOCID_COLUMN',
  1798: 'ER_INNODB_FT_WRONG_DOCID_INDEX',
  1799: 'ER_INNODB_ONLINE_LOG_TOO_BIG',
  1800: 'ER_UNKNOWN_ALTER_ALGORITHM',
  1801: 'ER_UNKNOWN_ALTER_LOCK',
  1802: 'ER_MTS_CHANGE_SOURCE_CANT_RUN_WITH_GAPS',
  1803: 'ER_MTS_RECOVERY_FAILURE',
  1804: 'ER_MTS_RESET_WORKERS',
  1805: 'ER_COL_COUNT_DOESNT_MATCH_CORRUPTED_V2',
  1806: 'ER_REPLICA_SILENT_RETRY_TRANSACTION',
  1807: 'ER_DISCARD_FK_CHECKS_RUNNING',
  1808: 'ER_TABLE_SCHEMA_MISMATCH',
  1809: 'ER_TABLE_IN_SYSTEM_TABLESPACE',
  1810: 'ER_IO_READ_ERROR',
  1811: 'ER_IO_WRITE_ERROR',
  1812: 'ER_TABLESPACE_MISSING',
  1813: 'ER_TABLESPACE_EXISTS',
  1814: 'ER_TABLESPACE_DISCARDED',
  1815: 'ER_INTERNAL_ERROR',
  1816: 'ER_INNODB_IMPORT_ERROR',
  1817: 'ER_INNODB_INDEX_CORRUPT',
  1818: 'ER_INVALID_YEAR_COLUMN_LENGTH',
  1819: 'ER_NOT_VALID_PASSWORD',
  1820: 'ER_MUST_CHANGE_PASSWORD',
  1821: 'ER_FK_NO_INDEX_CHILD',
  1822: 'ER_FK_NO_INDEX_PARENT',
  1823: 'ER_FK_FAIL_ADD_SYSTEM',
  1824: 'ER_FK_CANNOT_OPEN_PARENT',
  1825: 'ER_FK_INCORRECT_OPTION',
  1826: 'ER_FK_DUP_NAME',
  1827: 'ER_PASSWORD_FORMAT',
  1828: 'ER_FK_COLUMN_CANNOT_DROP',
  1829: 'ER_FK_COLUMN_CANNOT_DROP_CHILD',
  1830: 'ER_FK_COLUMN_NOT_NULL',
  1831: 'ER_DUP_INDEX',
  1832: 'ER_FK_COLUMN_CANNOT_CHANGE',
  1833: 'ER_FK_COLUMN_CANNOT_CHANGE_CHILD',
  1834: 'ER_FK_CANNOT_DELETE_PARENT',
  1835: 'ER_MALFORMED_PACKET',
  1836: 'ER_READ_ONLY_MODE',
  1837: 'ER_GTID_NEXT_TYPE_UNDEFINED_GROUP',
  1838: 'ER_VARIABLE_NOT_SETTABLE_IN_SP',
  1839: 'ER_CANT_SET_GTID_PURGED_WHEN_GTID_MODE_IS_OFF',
  1840: 'ER_CANT_SET_GTID_PURGED_WHEN_GTID_EXECUTED_IS_NOT_EMPTY',
  1841: 'ER_CANT_SET_GTID_PURGED_WHEN_OWNED_GTIDS_IS_NOT_EMPTY',
  1842: 'ER_GTID_PURGED_WAS_CHANGED',
  1843: 'ER_GTID_EXECUTED_WAS_CHANGED',
  1844: 'ER_BINLOG_STMT_MODE_AND_NO_REPL_TABLES',
  1845: 'ER_ALTER_OPERATION_NOT_SUPPORTED',
  1846: 'ER_ALTER_OPERATION_NOT_SUPPORTED_REASON',
  1847: 'ER_ALTER_OPERATION_NOT_SUPPORTED_REASON_COPY',
  1848: 'ER_ALTER_OPERATION_NOT_SUPPORTED_REASON_PARTITION',
  1849: 'ER_ALTER_OPERATION_NOT_SUPPORTED_REASON_FK_RENAME',
  1850: 'ER_ALTER_OPERATION_NOT_SUPPORTED_REASON_COLUMN_TYPE',
  1851: 'ER_ALTER_OPERATION_NOT_SUPPORTED_REASON_FK_CHECK',
  1852: 'ER_ALTER_OPERATION_NOT_SUPPORTED_REASON_IGNORE',
  1853: 'ER_ALTER_OPERATION_NOT_SUPPORTED_REASON_NOPK',
  1854: 'ER_ALTER_OPERATION_NOT_SUPPORTED_REASON_AUTOINC',
  1855: 'ER_ALTER_OPERATION_NOT_SUPPORTED_REASON_HIDDEN_FTS',
  1856: 'ER_ALTER_OPERATION_NOT_SUPPORTED_REASON_CHANGE_FTS',
  1857: 'ER_ALTER_OPERATION_NOT_SUPPORTED_REASON_FTS',
  1858: 'ER_SQL_REPLICA_SKIP_COUNTER_NOT_SETTABLE_IN_GTID_MODE',
  1859: 'ER_DUP_UNKNOWN_IN_INDEX',
  1860: 'ER_IDENT_CAUSES_TOO_LONG_PATH',
  1861: 'ER_ALTER_OPERATION_NOT_SUPPORTED_REASON_NOT_NULL',
  1862: 'ER_MUST_CHANGE_PASSWORD_LOGIN',
  1863: 'ER_ROW_IN_WRONG_PARTITION',
  1864: 'ER_MTS_EVENT_BIGGER_PENDING_JOBS_SIZE_MAX',
  1865: 'ER_INNODB_NO_FT_USES_PARSER',
  1866: 'ER_BINLOG_LOGICAL_CORRUPTION',
  1867: 'ER_WARN_PURGE_LOG_IN_USE',
  1868: 'ER_WARN_PURGE_LOG_IS_ACTIVE',
  1869: 'ER_AUTO_INCREMENT_CONFLICT',
  1870: 'WARN_ON_BLOCKHOLE_IN_RBR',
  1871: 'ER_REPLICA_MI_INIT_REPOSITORY',
  1872: 'ER_REPLICA_RLI_INIT_REPOSITORY',
  1873: 'ER_ACCESS_DENIED_CHANGE_USER_ERROR',
  1874: 'ER_INNODB_READ_ONLY',
  1875: 'ER_STOP_REPLICA_SQL_THREAD_TIMEOUT',
  1876: 'ER_STOP_REPLICA_IO_THREAD_TIMEOUT',
  1877: 'ER_TABLE_CORRUPT',
  1878: 'ER_TEMP_FILE_WRITE_FAILURE',
  1879: 'ER_INNODB_FT_AUX_NOT_HEX_ID',
  1880: 'ER_OLD_TEMPORALS_UPGRADED',
  1881: 'ER_INNODB_FORCED_RECOVERY',
  1882: 'ER_AES_INVALID_IV',
  1883: 'ER_FILE_CORRUPT',
  1884: 'ER_ERROR_ON_SOURCE',
  1885: 'ER_INCONSISTENT_ERROR',
  1886: 'ER_STORAGE_ENGINE_NOT_LOADED',
  1887: 'ER_GET_STACKED_DA_WITHOUT_ACTIVE_HANDLER',
  1888: 'ER_WARN_LEGACY_SYNTAX_CONVERTED',
  1889: 'ER_BINLOG_UNSAFE_FULLTEXT_PLUGIN',
  1890: 'ER_CANNOT_DISCARD_TEMPORARY_TABLE',
  1891: 'ER_FK_DEPTH_EXCEEDED',
  1892: 'ER_COL_COUNT_DOESNT_MATCH_PLEASE_UPDATE_V2',
  1893: 'ER_WARN_TRIGGER_DOESNT_HAVE_CREATED',
  1894: 'ER_REFERENCED_TRG_DOES_NOT_EXIST',
  1895: 'ER_EXPLAIN_NOT_SUPPORTED',
  1896: 'ER_INVALID_FIELD_SIZE',
  1897: 'ER_MISSING_HA_CREATE_OPTION',
  1898: 'ER_ENGINE_OUT_OF_MEMORY',
  1899: 'ER_PASSWORD_EXPIRE_ANONYMOUS_USER',
  1900: 'ER_REPLICA_SQL_THREAD_MUST_STOP',
  1901: 'ER_NO_FT_MATERIALIZED_SUBQUERY',
  1902: 'ER_INNODB_UNDO_LOG_FULL',
  1903: 'ER_INVALID_ARGUMENT_FOR_LOGARITHM',
  1904: 'ER_REPLICA_IO_THREAD_MUST_STOP',
  1905: 'ER_WARN_OPEN_TEMP_TABLES_MUST_BE_ZERO',
  1906: 'ER_WARN_ONLY_SOURCE_LOG_FILE_NO_POS',
  1907: 'ER_QUERY_TIMEOUT',
  1908: 'ER_NON_RO_SELECT_DISABLE_TIMER',
  1909: 'ER_DUP_LIST_ENTRY',
  1910: 'ER_SQL_MODE_NO_EFFECT',
  3169: 'ER_SESSION_WAS_KILLED',
  4031: 'ER_CLIENT_INTERACTION_TIMEOUT',
} as const;
